"""Parcel C's acceptance criterion: the Postgres connector and the model-free seed.

**Rewritten 2026-08-03 against Postgres.** The previous version of this file was written
against `SqliteConnector`, it passed cleanly, and it was measuring a connector the project
no longer supports (decision #40). That is a **design-holder** error, not an
implementer's, and it is a different failure from the one the contract-first rule exists to
prevent: authoring a contract before the implementation stops an implementer grading
themselves, and does nothing about the design holder scoping it wrong. A contract can be
honest, thorough, passed, and about the wrong subject.

**Do not edit this file to make it pass.** If a test looks wrong, stop and say so.

Three things carry this parcel, and the first two are new here.

**The error taxonomy is keyed on SQLSTATE, never on message text.** The predecessor's
classifier was a four-marker regex over exception prose, defaulting to `ConnectionError`,
and an adversarial review found it wrong in *both* directions — `no such function` and a
bad arity landed in the crash stratum, a corrupt database file landed in the wrong-answer
stratum. That was not sloppiness; SQLite reports faults as prose and there was nothing
else to match on. Postgres gives structured codes, so the distinction that decides whether
a turn is a crash or a wrong answer — the distinction whose miscoding retired the
pre-2026-07-25 numbers — becomes a lookup:

* class ``42`` — syntax error or access-rule violation. **A query fault.** The statement
  reached the engine and the engine rejected it.
* class ``08`` — connection exception. **Infrastructure.**
* classes ``53`` / ``57`` — insufficient resources, operator intervention.
  **Infrastructure.**

A regex over English can be wrong in both directions. A SQLSTATE class cannot.

**A query `govern` permits must be one the connector executes.** This is the cross-parcel
property that nobody owned, and its absence meant the intersection of "govern permits" and
"the connector executes" was **empty** for the whole of 2026-08-03 — `govern` licenses
`{schema}.{physical_name}`, SQLite rejected the qualified form, and nothing tested the
pair. It did not surface because the grader re-executed outside governance. Postgres-only
makes it native; this test is what keeps it that way.

**The seed is what makes retrieval measurable before a curator exists.** ADR 0005's claim
that "steps 6-9 are measurable with no model at all" rests entirely on it, so it is
asserted at the socket rather than trusted.

**When no server is reachable these tests skip with a printed reason**, never silently:
the reason is the whole point, and a silent skip and a pass produce the same green tick.
"""

from __future__ import annotations

import os
import pathlib
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from contracts import needs  # noqa: E402

pytestmark = [needs("C")]

#: SQLSTATEs that must classify as a **query fault**, with the statement that produces
#: each. Every one of these was misclassified as infrastructure by the predecessor.
QUERY_FAULTS: tuple[tuple[str, str, str], ...] = (
    ("42P01", "undefined_table", "SELECT 1 FROM no_such_table_xyz"),
    ("42703", "undefined_column", "SELECT no_such_column_xyz FROM {t}"),
    ("42601", "syntax_error", "SELEKT 1"),
    ("42883", "undefined_function", "SELECT no_such_fn_xyz(1)"),
    ("42883", "wrong_arity", "SELECT abs(1, 2)"),
)


def _dsn() -> str:
    """The DSN, from the environment or `.env`. Never logged — it carries credentials."""
    dsn = os.environ.get("GOVERNED_BI_PG_DSN") or os.environ.get("PG_RENAME_DECOY_DSN")
    if dsn:
        return dsn
    env = pathlib.Path(__file__).resolve().parent.parent.parent / ".env"
    if env.exists():
        for line in env.read_text(encoding="utf-8").splitlines():
            if line.strip().startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            if key.strip() in ("GOVERNED_BI_PG_DSN", "PG_RENAME_DECOY_DSN"):
                return value.strip().strip("\"'")
    return ""


@pytest.fixture(scope="module")
def dsn() -> str:
    """Skip loudly when there is no server. The reason must reach the reader."""
    value = _dsn()
    if not value:
        pytest.skip(
            "no Postgres DSN: set GOVERNED_BI_PG_DSN or PG_RENAME_DECOY_DSN. "
            "Parcel C is Postgres-only (decision #40) and a connector cannot be "
            "tested without a server; these tests are not optional, they are pending."
        )
    import psycopg

    try:
        with psycopg.connect(value, connect_timeout=5):
            pass
    except Exception as err:  # pragma: no cover - environment dependent
        pytest.skip(f"Postgres unreachable ({type(err).__name__}); see the DSN's host")
    return value


@pytest.fixture
def fixture_schema(dsn):
    """A throwaway schema with three rows and one FK.

    Its own schema, dropped afterwards, because the reachable server holds the real
    obfuscated BIRD data and a test that writes into it would corrupt the eval corpus.
    """
    import psycopg

    name = "gbi_contract_probe"
    with psycopg.connect(dsn, autocommit=True) as con:
        con.execute(f'DROP SCHEMA IF EXISTS "{name}" CASCADE')
        con.execute(f'CREATE SCHEMA "{name}"')
        con.execute(f'CREATE TABLE "{name}".customers (id integer PRIMARY KEY, email text)')
        con.execute(
            f'CREATE TABLE "{name}".orders (id integer PRIMARY KEY, '
            f'cid integer REFERENCES "{name}".customers(id), amount numeric)'
        )
        con.execute(f"INSERT INTO \"{name}\".customers VALUES (1,'a@x'),(2,'b@x'),(3,'c@x')")
    try:
        yield name
    finally:
        with psycopg.connect(dsn, autocommit=True) as con:
            con.execute(f'DROP SCHEMA IF EXISTS "{name}" CASCADE')


@pytest.fixture
def connector(dsn, fixture_schema):
    from governed_bi.datasource.postgres import PostgresConnector  # type: ignore[import-not-found]

    return PostgresConnector(dsn)


# ── the connector executes, and it is not a stub ──────────────────────────────


def test_execute_returns_columns_rows_and_truncated(connector, fixture_schema) -> None:
    """The predecessor never touched Postgres, so five of six methods could raise
    ``ConnectionError("not exercised in this tranche")`` and the suite stayed green."""
    columns, rows, truncated = connector.execute(
        f'SELECT id, email FROM "{fixture_schema}".customers ORDER BY id'
    )
    assert list(columns) == ["id", "email"]
    assert len(rows) == 3
    assert truncated is False


def test_truncated_comes_from_a_max_rows_plus_one_fetch(connector, fixture_schema) -> None:
    """A caller that must compare ``len(rows) == max_rows`` cannot tell "exactly at the
    cap" from "cut off". Three of four v1 grader-ceiling misses were row-cap related."""
    sql = f'SELECT id FROM "{fixture_schema}".customers ORDER BY id'
    assert connector.execute(sql, max_rows=2)[2] is True
    assert connector.execute(sql, max_rows=3)[2] is False, "exactly at the cap is not truncated"
    assert connector.execute(sql, max_rows=4)[2] is False


# ── the error taxonomy, keyed on SQLSTATE ─────────────────────────────────────


@pytest.mark.parametrize("sqlstate,label,sql", QUERY_FAULTS, ids=[q[1] for q in QUERY_FAULTS])
def test_a_class_42_sqlstate_is_a_query_fault(connector, fixture_schema, sqlstate, label, sql) -> None:
    """Class ``42`` means the statement reached the engine and was rejected. That is a
    **wrong answer**, not a crash, and the two land in different strata of every arm
    comparison.

    ``undefined_function`` and ``wrong_arity`` are the ones that matter most: they are the
    commonest generation errors on obfuscated schemas, and the predecessor put both in the
    crash stratum.
    """
    from governed_bi.datasource import errors  # type: ignore[import-not-found]

    with pytest.raises(errors.QueryError) as caught:
        connector.execute(sql.format(t=f'"{fixture_schema}".customers'))
    assert getattr(caught.value, "sqlstate", None) == sqlstate, (
        f"{label}: the error must carry its SQLSTATE, so a reader can classify it "
        "without parsing prose"
    )


def test_a_class_08_sqlstate_is_infrastructure(dsn) -> None:
    """The complement, and without it a connector that raised ``QueryError`` for
    everything would satisfy every test above."""
    from governed_bi.datasource import errors  # type: ignore[import-not-found]
    from governed_bi.datasource.postgres import PostgresConnector  # type: ignore[import-not-found]

    unreachable = PostgresConnector("postgresql://nobody@127.0.0.1:1/none")
    with pytest.raises(errors.ConnectionError) as caught:
        unreachable.execute("SELECT 1")

    # The class alone is not enough, and the strict xfail proved it: this test XPASSED
    # against a stub whose every method raises ConnectionError. A test satisfied by "raise
    # ConnectionError unconditionally" cannot tell a working classifier from no classifier
    # at all -- the same shape as v1's gold gate passing with the comparison reversed. So
    # the error must carry the code it classified on, which a stub has no way to produce.
    state = getattr(caught.value, "sqlstate", None)
    assert state and str(state).startswith("08"), (
        f"expected a class-08 SQLSTATE on the error, got {state!r}. Without it, this "
        "test is satisfied by a connector that raises ConnectionError for everything, "
        "including for query faults."
    )


def test_classification_reads_the_code_not_the_message(connector, fixture_schema) -> None:
    """The structural form of the rule, and the one that survives a refactor.

    The specific bug is easy to fix in a way that leaves the next one reachable. Assert
    that the classifier is a **lookup on SQLSTATE**: a query fault whose message contains
    the word "connection", and a connection fault whose message does not, must both
    classify correctly. If the implementation greps prose, one of these inverts.
    """
    from governed_bi.datasource import errors  # type: ignore[import-not-found]

    with pytest.raises(errors.QueryError):
        connector.execute("SELECT connection_is_not_a_function_xyz(1)")


def test_introspection_classifies_its_own_failures(dsn) -> None:
    """``introspect`` / ``list_tables`` / ``describe_table`` leaked raw driver exceptions in
    the predecessor, so they escaped the taxonomy entirely — a failure there is neither a query
    fault nor infrastructure, it is unclassified."""
    from governed_bi.datasource import errors  # type: ignore[import-not-found]
    from governed_bi.datasource.postgres import PostgresConnector  # type: ignore[import-not-found]

    unreachable = PostgresConnector("postgresql://nobody@127.0.0.1:1/none")
    with pytest.raises((errors.ConnectionError, errors.QueryError)):
        unreachable.introspect("public")


# ── a dead connection must not survive the statement that killed it ───────────


def _connector_with(conn: object) -> object:
    """A ``PostgresConnector`` over a fake handle, with reconnects counted.

    No DSN and no server: these two tests are about what the connector does with a handle the
    driver has given up on, and that needs a handle that fails on demand rather than a
    database. The Postgres-gated tests above cover the SQLSTATE paths against a real server.
    """
    from governed_bi.datasource.postgres import (  # type: ignore[import-not-found]
        PostgresConnector,
    )

    class _Fake(PostgresConnector):
        def __init__(self) -> None:
            self._dsn = "postgresql://unused"
            self._max_rows = 10
            self._conn = None
            self.connects = 0

        def _connect(self):  # noqa: ANN202
            if self._conn is None:
                self.connects += 1
                self._conn = conn
            return self._conn

    return _Fake()


def test_one_connection_blip_does_not_poison_the_rest_of_the_run() -> None:
    """Audit §9.1. ``execute`` never cleared ``_conn``, and ``_connect`` returned it anyway.

    ``close()`` was the only writer of ``_conn = None`` and it is reached only from
    ``__exit__`` / ``__del__``, so a handle the driver had abandoned was reused for every
    remaining statement. On a 1 351-question eval arm that is one network blip deciding
    whether the rest of the run's data is real.

    **And the failure was invisible**, which is the half that matters more: psycopg raises
    ``the connection is closed`` with ``sqlstate=None``, so the classifier fell past the
    class-42 test *and* the 08/53/57 test and returned ``QueryError`` — an infrastructure
    fault recorded as *the model wrote bad SQL*, for every question after the blip.
    """
    import psycopg

    from governed_bi.datasource import errors  # type: ignore[import-not-found]

    class _Dead:
        closed = False
        broken = False

        def execute(self, sql, *args, **kwargs):  # noqa: ANN001, ANN202
            raise psycopg.OperationalError("the connection is closed")

        def close(self) -> None:
            pass

    connector = _connector_with(_Dead())
    for _ in range(3):
        with pytest.raises(errors.ConnectionError) as caught:
            connector.execute("SELECT 1")
        assert caught.value.sqlstate, "an infrastructure fault must carry a class-08 code"
        assert connector._conn is None, "the dead handle survived the statement that killed it"

    assert connector.connects == 3, (
        f"reconnected {connector.connects} time(s) in three calls; the cached handle is still "
        "being reused after a failure"
    )


def test_a_client_side_fault_that_is_not_the_connection_is_still_a_query_fault() -> None:
    """The paired negative. Invalidating on *every* SQLSTATE-less error would be too much.

    A ``ProgrammingError`` with no SQLSTATE is a fault in the call, not in the socket, and
    treating it as infrastructure would drop a live connection and relabel a real statement
    problem — the same conflation as the original defect, pointing the other way. The
    classification is on structured driver state (``closed`` / ``broken``, and the DB-API's
    ``OperationalError`` / ``ProgrammingError`` split), never on the message.
    """
    import psycopg

    from governed_bi.datasource import errors  # type: ignore[import-not-found]

    class _Fussy:
        closed = False
        broken = False

        def execute(self, sql, *args, **kwargs):  # noqa: ANN001, ANN202
            # No sqlstate: psycopg raises this client-side, before the server sees anything.
            raise psycopg.ProgrammingError("the connection cannot be used in this context")

        def close(self) -> None:
            pass

    connector = _connector_with(_Fussy())
    with pytest.raises(errors.QueryError):
        connector.execute("SELECT 1")
    assert connector._conn is not None, (
        "a statement fault must not discard a working connection — and the message here "
        "contains the word 'connection', so a prose-matching classifier inverts this"
    )


def test_the_sqlite_adapter_classifies_by_code_and_not_by_prose(tmp_path) -> None:
    """Audit §9.2, verified. The prose regex misclassified two faults that matter.

    ``test_classification_reads_the_code_not_the_message`` above states this rule and is
    **Postgres-gated**, so it never ran against the adapter that failed it — and its literal
    example, ``SELECT connection_is_not_a_function_xyz(1)``, raised *no such function*, which
    matched none of ``no such column|no such table|syntax error|ambiguous column``. So a query
    fault was reported as the database being unreachable.

    The second one is worse: a write on the read-only connection raises ``SQLITE_READONLY``,
    also unmatched, so **governance stopping a write was recorded as infrastructure being
    down**. A control firing correctly, filed as an outage.

    This test is not gated. That is the point of it: the class of defect here is a rule asserted
    in one adapter's suite and unenforced in the other's.
    """
    import sqlite3

    from governed_bi.datasource import errors  # type: ignore[import-not-found]
    from governed_bi.datasource.sqlite import SqliteConnector  # type: ignore[import-not-found]

    path = tmp_path / "taxonomy.db"
    seed = sqlite3.connect(path)
    seed.execute("CREATE TABLE t (a INTEGER)")
    seed.commit()
    seed.close()

    connector = SqliteConnector(path)
    statement_faults = [
        # The Postgres test's own example. Its message contains "connection", so a
        # prose-matching classifier inverts it in both directions at once.
        "SELECT connection_is_not_a_function_xyz(1)",
        "SELECT nope FROM t",
        "SELEC 1",
        "SELECT * FROM no_such_table",
        # The read-only guard firing. SQLITE_READONLY is a verdict on the statement.
        "INSERT INTO t VALUES (1)",
    ]
    for sql in statement_faults:
        with pytest.raises(errors.QueryError, match=r".*") as caught:
            connector.execute(sql)
        assert not isinstance(caught.value, errors.ConnectionError), sql

    # And the paired positive: a genuine infrastructure code must still be infrastructure.
    missing = SqliteConnector(tmp_path / "not-here.db")
    with pytest.raises(errors.ConnectionError):
        missing.execute("SELECT 1")


# ── the cross-parcel property that nobody owned ───────────────────────────────


def test_a_statement_govern_permits_is_one_the_connector_executes(connector, fixture_schema) -> None:
    """#39a, turned into a test so it cannot come back.

    ``govern`` licenses ``{schema}.{physical_name}`` deliberately — a pooled corpus repeats
    table names across schemas. For the whole of 2026-08-03 the only working connector
    rejected that qualified form, so **the intersection of "govern permits" and "the
    connector executes" was empty**, and nothing noticed because the grader re-executed
    outside governance.

    Postgres makes the two agree natively. This asserts the agreement rather than assuming
    it, because it is the one property that lives between two parcels and belongs to
    neither.
    """
    from governed_bi.corpus.analyst import analyst_corpus_from_keys  # type: ignore[import-not-found]
    from governed_bi.govern.check import check  # type: ignore[import-not-found]

    sql = f'SELECT count(*) FROM "{fixture_schema}".customers'
    verdict = check(
        f"SELECT count(*) FROM {fixture_schema}.customers",
        licensed=frozenset({f"{fixture_schema}.customers"}),
        corpus=analyst_corpus_from_keys(allowed=(f"{fixture_schema}.customers.id",)),
    )
    assert verdict["passed"] is True, verdict
    columns, rows, _ = connector.execute(sql)
    assert rows[0][0] == 3, "govern permitted it; the connector must be able to run it"


# ── the seed ──────────────────────────────────────────────────────────────────


def test_every_seeded_asset_has_a_non_empty_summary(connector, fixture_schema) -> None:
    """One empty summary is one asset that can never be retrieved — and it would present
    as a retrieval failure rather than a seeding gap."""
    from governed_bi.corpus.seed import seed  # type: ignore[import-not-found]

    assets, problems = seed(connector.introspect(fixture_schema), schema=fixture_schema)
    assert assets, problems
    assert all(a.summary and a.summary.strip() for a in assets)


def test_the_seed_covers_every_table_and_column(connector, fixture_schema) -> None:
    from governed_bi.corpus.seed import seed  # type: ignore[import-not-found]

    assets, _ = seed(connector.introspect(fixture_schema), schema=fixture_schema)
    kinds: dict[str, int] = {}
    for a in assets:
        kinds[a.asset_type] = kinds.get(a.asset_type, 0) + 1
    assert kinds.get("table") == 2
    assert kinds.get("column") == 5  # 2 customers + 3 orders


def test_the_seed_makes_no_model_call(connector, fixture_schema, monkeypatch) -> None:
    """Asserted at the seam rather than trusted. Introspection is already done by the
    fixture, so the seed itself must open nothing."""
    import socket

    intro = connector.introspect(fixture_schema)

    def refuse(*args, **kwargs):  # pragma: no cover - the point is that it is not hit
        raise AssertionError("the seed opened a socket; it must be model-free")

    monkeypatch.setattr(socket, "socket", refuse)
    monkeypatch.setattr(socket, "create_connection", refuse)

    from governed_bi.corpus.seed import seed  # type: ignore[import-not-found]

    assets, _ = seed(intro, schema=fixture_schema)
    assert assets


def test_the_seed_is_deterministic(connector, fixture_schema) -> None:
    """``corpus_content_hash`` is the treatment identity, so a nondeterministic seed makes
    every arm look differently treated and passes the delivery gate for the wrong reason."""
    from governed_bi.corpus.seed import seed  # type: ignore[import-not-found]

    intro = connector.introspect(fixture_schema)
    first, _ = seed(intro, schema=fixture_schema)
    second, _ = seed(intro, schema=fixture_schema)
    assert [a.id for a in first] == [a.id for a in second]
    assert [a.summary for a in first] == [a.summary for a in second]


def test_seeded_assets_pass_corpus_validation(connector, fixture_schema) -> None:
    """The cross-parcel check most likely to be skipped, because it needs both halves. A
    seed whose output the validator rejects means the corpus cannot be built at all — and
    each parcel's own tests would still pass."""
    from governed_bi.corpus.seed import seed  # type: ignore[import-not-found]
    from governed_bi.corpus.validate import problems_with  # type: ignore[import-not-found]

    assets, _ = seed(connector.introspect(fixture_schema), schema=fixture_schema)
    assert not [p for a in assets for p in problems_with(a)]
