"""Parcel C's acceptance criterion: the connector interface and the model-free seed.

**Do not edit this file to make it pass.** It is the contract, authored before the
implementation. If a test looks wrong, say so and stop.

Specification: ``docs/plans/v2-layer-handoffs.md`` §4, ``ports.Connector``, ADR 0005
§1.4. Two things carry this parcel:

**The seed is what makes retrieval measurable before a curator exists.** ADR 0005's
"steps 6-9 are measurable with no model at all" is true only because the seed
guarantees a non-empty ``summary`` on **every** asset from introspection alone. Any
model call in the seed path falsifies that claim, so it is asserted here rather than
assumed.

**``truncated`` is a fact the caller receives, never one it infers.** Derived from a
``max_rows + 1`` limit. The alternative — compare a row count against the cap — makes
every caller need to know the cap in order to read the count, and three of v1's four
grader-ceiling misses were row-cap related.

The subtlest requirement is the error taxonomy. SQLite wraps *"no such column"* in
``OperationalError``, so a connector that maps that exception family to
"infrastructure failure" **hides wrong answers as crashes** — and crashes and wrong
answers land in different strata of every arm comparison. ``register/stages.py``
already encodes the classification; this parcel's job is to hand it inputs it can
classify, not to classify.
"""

from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from contracts import needs  # noqa: E402

pytestmark = needs("C")


@pytest.fixture
def db(tmp_path) -> Path:
    """Three rows, two columns, one FK. Small enough to reason about exactly."""
    path = tmp_path / "t.db"
    con = sqlite3.connect(path)
    try:
        con.executescript(
            """
            CREATE TABLE customers (id INTEGER PRIMARY KEY, email TEXT);
            CREATE TABLE orders (
                id INTEGER PRIMARY KEY, cid INTEGER REFERENCES customers(id), amount REAL
            );
            INSERT INTO customers (id, email) VALUES (1,'a@x'),(2,'b@x'),(3,'c@x');
            """
        )
        con.commit()
    finally:
        con.close()
    return path


@pytest.fixture
def connector(db):
    from governed_bi.datasource.sqlite import SqliteConnector  # type: ignore[import-not-found]

    return SqliteConnector(db)


# ── the connector interface ──────────────────────────────────────────────────


def test_execute_returns_columns_rows_and_truncated(connector) -> None:
    columns, rows, truncated = connector.execute("SELECT id, email FROM customers ORDER BY id")
    assert list(columns) == ["id", "email"]
    assert len(rows) == 3
    assert truncated is False


def test_truncated_is_true_at_the_cap_without_the_caller_knowing_the_cap(connector) -> None:
    """The whole point of returning the flag. A caller that has to compare
    ``len(rows) == max_rows`` cannot tell "exactly at the cap" from "cut off", and the
    ``max_rows + 1`` fetch is what resolves that ambiguity."""
    _, rows, truncated = connector.execute("SELECT id FROM customers ORDER BY id", max_rows=2)
    assert len(rows) == 2
    assert truncated is True


def test_exactly_at_the_cap_is_not_truncated(connector) -> None:
    """The boundary, and the reason ``max_rows + 1`` rather than ``max_rows`` is
    fetched. Reporting three-of-three as truncated would make every full result look
    cut off."""
    _, rows, truncated = connector.execute("SELECT id FROM customers ORDER BY id", max_rows=3)
    assert len(rows) == 3
    assert truncated is False


def test_a_bad_column_surfaces_as_a_query_error_not_an_infrastructure_error(connector) -> None:
    """SQLite wraps "no such column" in ``OperationalError``. A connector that maps that
    family to "the database is unreachable" hides a **wrong answer** as a **crash**, and
    those land in different strata of every arm comparison.

    The error must be distinguishable from a connection failure. How is the
    implementer's call; conflating them is not.
    """
    from governed_bi.datasource import errors  # type: ignore[import-not-found]

    with pytest.raises(errors.QueryError):
        connector.execute("SELECT nonexistent_column FROM customers")


def test_an_unreachable_database_is_a_different_error(tmp_path) -> None:
    """The complement. If both raise ``QueryError`` the distinction above is cosmetic."""
    from governed_bi.datasource import errors  # type: ignore[import-not-found]
    from governed_bi.datasource.sqlite import SqliteConnector  # type: ignore[import-not-found]

    broken = SqliteConnector(tmp_path / "no" / "such" / "path.db")
    with pytest.raises(errors.ConnectionError):
        broken.execute("SELECT 1")


# ── introspection ────────────────────────────────────────────────────────────


def test_introspection_reports_tables_columns_types_and_declared_fks(connector) -> None:
    intro = connector.introspect()
    tables = {t.physical_name for t in intro.tables}
    assert tables == {"customers", "orders"}
    assert any(fk.from_table == "orders" and fk.to_table == "customers" for fk in intro.foreign_keys)
    orders = next(t for t in intro.tables if t.physical_name == "orders")
    assert {c.physical_name for c in orders.columns} == {"id", "cid", "amount"}
    assert all(c.physical_type for c in orders.columns), "a column with no type is unusable"


# ── the seed ─────────────────────────────────────────────────────────────────


def test_every_seeded_asset_has_a_non_empty_summary(connector) -> None:
    """The claim ADR 0005 rests on: retrieval is measurable with no model at all,
    *because* the seed leaves no asset unindexed. One empty summary is one asset that
    can never be retrieved, and it would look like a retrieval failure rather than a
    seeding gap."""
    from governed_bi.corpus.seed import seed  # type: ignore[import-not-found]

    assets, problems = seed(connector.introspect(), schema="beer_factory")
    assert assets, problems
    assert all(a.summary and a.summary.strip() for a in assets)


def test_the_seed_covers_every_table_and_every_column(connector) -> None:
    """Coverage is the property, not asset count. A seed that skips a column makes that
    column unrankable, which ADR 0005 names as the missing path on obfuscated schemas.
    """
    from governed_bi.corpus.seed import seed  # type: ignore[import-not-found]

    assets, _ = seed(connector.introspect(), schema="beer_factory")
    kinds = {}
    for a in assets:
        kinds.setdefault(a.asset_type, []).append(a)
    assert len(kinds.get("table", [])) == 2
    assert len(kinds.get("column", [])) == 5  # 2 customers + 3 orders


def test_the_seed_makes_no_model_call(connector, monkeypatch) -> None:
    """Asserted at the seam rather than trusted. Any network egress from the seed path
    falsifies the "measurable with no model" claim, and that claim is why steps 6-9 of
    ADR 0005's build order come before a curator exists.
    """
    import socket

    def refuse(*args, **kwargs):  # pragma: no cover - the point is that it is not hit
        raise AssertionError("the seed opened a socket; it must be model-free")

    monkeypatch.setattr(socket, "socket", refuse)
    monkeypatch.setattr(socket, "create_connection", refuse)

    from governed_bi.corpus.seed import seed  # type: ignore[import-not-found]

    assets, _ = seed(connector.introspect(), schema="beer_factory")
    assert assets


def test_the_seed_is_deterministic(connector) -> None:
    """Two runs over one schema must produce identical assets, because
    ``corpus_content_hash`` is the treatment identity and a nondeterministic seed makes
    every arm look differently treated — passing the delivery gate for the wrong
    reason."""
    from governed_bi.corpus.seed import seed  # type: ignore[import-not-found]

    first, _ = seed(connector.introspect(), schema="beer_factory")
    second, _ = seed(connector.introspect(), schema="beer_factory")
    assert [a.id for a in first] == [a.id for a in second]
    assert [a.summary for a in first] == [a.summary for a in second]


def test_seeded_assets_pass_corpus_validation(connector) -> None:
    """The cross-parcel check, and the one most likely to be skipped because it needs
    both halves. A seed whose output the validator rejects means the corpus cannot be
    built at all — and each parcel's own tests would pass."""
    from governed_bi.corpus.seed import seed  # type: ignore[import-not-found]
    from governed_bi.corpus.validate import problems_with  # type: ignore[import-not-found]

    assets, _ = seed(connector.introspect(), schema="beer_factory")
    assert not [p for a in assets for p in problems_with(a)]
