"""Adapter construction for ``tests/model/test_embedder_contract.py``.

**Here rather than at that file's module level.** Its header says *"Do not edit this file
to make it pass"*, and the twelve bodies an implementer writes are the sanctioned edit —
module-level scaffolding is not. It also sits beside ``tests/contracts.py`` for the same
reason that file does: the contract already puts ``tests/`` on ``sys.path``, so a body can
reach this with one local import and no new import at the top of the specification.

**The skip is loud, and that is the whole job of this module.** ``ADAPTERS`` is
``("deterministic", "openai")``, so a green run *claims* two adapters satisfied one
contract — which is the only reason the port earns its existence at all. Without a key the
OpenAI half cannot run, and a silent skip turns "we tested one adapter" into "we tested
two". So :func:`make_embedder` skips with the variable's **name** in the reason (never its
value) and ``-rs`` prints it. The same argument as ``tests/contracts.py``'s three-state
parcel register: a skipped thing and a passing thing look identical under ``pytest -q``.
"""

from __future__ import annotations

from typing import Any

import pytest

from governed_bi.model import OPENAI_API_KEY_VAR, DeterministicEmbedder, OpenAIEmbedder

#: Small on purpose. Every OpenAI-backed body in the contract pays real tokens, and the
#: machine's per-minute quota is shared with other work, so the fixtures are a handful of
#: short strings at a narrow width. 64 is wide enough that the hashing adapter's bucket
#: collisions do not swamp a summary-length text, and narrow enough to keep the shortened
#: ``text-embedding-3-large`` responses small.
NARROW_DIMENSIONS = 64

#: Crossed by the ordering body with seven inputs. Batching is the only place order can
#: break, so the fixture has to straddle a boundary; ``DEFAULT_BATCH_SIZE`` is 256 and
#: embedding 257 strings to prove it would cost real money for no extra information.
SMALL_BATCH = 4


def openai_available() -> bool:
    """Whether the OpenAI adapter can run. Reads presence only, never the value."""
    import os

    return bool(os.environ.get(OPENAI_API_KEY_VAR))


def make_embedder(adapter: str, **kwargs: Any) -> Any:
    """Construct ``adapter`` by name, or skip loudly when its provider is unreachable.

    Construction never issues a request: ``OpenAIEmbedder`` resolves its served identity
    lazily, so a body that only checks a refusal costs nothing.
    """
    if adapter == "deterministic":
        return DeterministicEmbedder(**kwargs)
    if adapter == "openai":
        if not openai_available():
            pytest.skip(
                f"{OPENAI_API_KEY_VAR} is not set in the environment. THIS CONTRACT RAN "
                "AGAINST ONE ADAPTER, NOT TWO: only DeterministicEmbedder was exercised, "
                "so the port's 'two independent implementations satisfy one contract' "
                "claim is unverified for OpenAIEmbedder on this run."
            )
        return OpenAIEmbedder(**kwargs)
    raise AssertionError(f"unknown adapter {adapter!r}; ADAPTERS is out of sync")
