"""Parcel J's acceptance criterion: the HTTP surface, per ADR 0007.

**Written 2026-08-03, before `src/governed_bi/api/` exists.** ADR 0007 is the design; this
file is what makes it checkable. `tools/check_imports.py` has declared an `api` layer since
before v1 was deleted, and nothing has ever been in it.

**Do not edit this file to make it pass.** If a test looks wrong, stop and say so.

Two rules run through all of it, and both are governance rather than plumbing:

1. **A client may not write the run's claims about itself.** `run_id`, `corpus_content_hash`,
   `knobs_resolved` and their siblings are what every quotability gate reads. A
   client-settable provenance field is a forgeable record — the same reason ADR 0006 says no
   tool writes to `licensed`.
2. **A field the engine does not observe must not be invented at the boundary.** The UI wants
   `tier`, `safety_clearance` and `semantic_assurance`; v2 has none of them. Synthesizing one
   in the server would put a reliability claim with nothing behind it on the most prominent
   badge in the interface, which is the defect class the rewrite existed to remove.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from contracts import needs  # noqa: E402

#: A specification with no body. Per test, never module-level.
UNWRITTEN = pytest.mark.xfail(strict=True, reason="contract specified, body not yet written")

pytestmark = [needs("J")]

#: `src/governed_bi`, for the structural assertions. Some of these must be structural: a
#: behavioural test that "the server does not synthesize a tier" passes for every input the
#: test happens to try, and says nothing about the next one.
SRC = Path(__file__).resolve().parent.parent.parent / "src" / "governed_bi"


# ── the record is the run's, not the client's ─────────────────────────────────


@UNWRITTEN
def test_a_client_cannot_set_any_provenance_field() -> None:
    """ADR 0007 §2. The most important test here.

    The UI submits one key — `{messages: [{type: "human", content}]}` — and the record
    requires fifteen fields. Something server-side must mint the rest. The failure mode is
    not that it forgets: it is that it **merges** what the client sent.

    `run_id`, `turn_id`, `question_id`, `corpus_content_hash`, `prompt_set_hash`,
    `knobs_resolved` are the run's own claims about itself, and `measure/gates.py` reads them
    to decide whether a run is quotable. A client that can set `corpus_content_hash` can make
    two different corpora report as one, which is a forged comparison rather than a bad one.

    **Fixture shape.** Invoke the graph the way the server does, with a client payload that
    sets every required field to a recognisable sentinel. Assert **no sentinel reaches the
    record** — field by field, from `required_keys()`, not from a hand-written list. Assert
    the turn still succeeds: silently dropping the whole turn would also pass a
    "no sentinel survived" check.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_the_graph_is_loadable_the_way_langgraph_json_loads_it() -> None:
    """`langgraph.json` names a factory by file path, and LangGraph Server can only put
    **JSON** in `config.configurable` — while every node needs live objects: `policy` (a
    dataclass, subscripted unguarded at `guard.py:21`), `agent_model`, `corpus`, `index`,
    `structure`, `connector`, `assets_by_id`.

    So the factory must close over a `Session`. Assert it does: build the graph the way the
    server entry does, invoke it with a `configurable` containing **only JSON**, and assert
    the turn reaches a terminal path. A `KeyError` on `policy` mid-run is the failure this
    catches, and it is the failure that would only appear on the first real request.

    Assert `langgraph.json` itself parses and its `graphs` key names `serve` — that string is
    the UI's `ASSISTANT_ID` default, so a rename silently 404s every chat request.
    """
    pytest.fail("not implemented: see docstring")


# ── /capabilities: observations, and false is a real answer ───────────────────


@UNWRITTEN
def test_capabilities_reports_what_is_true_not_what_is_configured() -> None:
    """It is the UI's **first** request; without it the chat panel pins at a skeleton
    forever, so this route failing is indistinguishable from the whole backend being down.

    `has_live_model` must be false when no model is configured, and `can_clarify` false when
    the `ask_user` tool is not bound. Assert the false cases, because the true ones pass for
    a server that hard-codes `true` — and a hard-coded `has_live_model` is the stub-path
    defect again, one layer out: the interface would promise a model that will never answer.

    `can_edit` is **false** for now: the curator is out of scope, and reporting it true would
    put an edit button in front of a route that does not exist.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_the_pages_that_do_not_need_a_model_work_without_one() -> None:
    """`/health`, `/schema`, `/corpus/assets`, `/graph` and `/knowledge-graph` are
    **ungated** in the UI — nothing checks a capability before calling them, so a 500 from
    any of them is a broken page rather than a degraded one.

    All five are projections of the `Session`'s assets and, now that `CorpusStructure`
    exists, the two graph routes are edges plus assets rather than new work. None needs a
    model or an API key.

    Assert they answer on a session built with **no** `agent_model`. This is what makes the
    corpus browsable before anyone has paid for a single token.
    """
    pytest.fail("not implemented: see docstring")


# ── nothing is invented at the boundary ──────────────────────────────────────


@UNWRITTEN
def test_the_api_never_synthesizes_a_reliability_field() -> None:
    """ADR 0007 §3, asserted **structurally**, because that is the only way it survives.

    A behavioural test — "this response has no `tier`" — is true of the inputs it tried. The
    claim is about the code: `tier`, `safety_clearance` and `semantic_assurance` must not
    appear as *produced* values anywhere under `api/`.

    Grep `SRC / "api"` for them. If a future decision earns a reliability tier from a
    measurement, this test is the thing that must be deliberately changed, and that is the
    point: it makes reintroducing the badge a decision rather than a diff nobody read.

    v1's `docs/openapi.json` is still tracked and still specifies the old `AnswerView`. It is
    the spec-of-record for the twelve *routes*, **not** for the answer shape.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_the_answer_on_the_wire_is_the_engine_s_answer() -> None:
    """The complement, and it needs both halves to mean anything.

    The wire shape is v2's: `{outcome, text, failed_stage, error_type, refused_by, record}`,
    and `record` is exactly `project()`'s output. Assert the served payload's `record` keys
    equal `record_keys()` — derived, not listed. A server that passes through a subset is the
    silent-degradation shape: the provenance drawer would render, with fields missing and
    nothing saying so.

    And assert `text` is **null on the answered path** and non-null on refuse (ADR 0007 §4:
    `text` is system copy; the model's answer is the last `AIMessage`). That asymmetry looked
    like a bug for a day; asserting it is what stops someone "fixing" it into two fields that
    must agree.
    """
    pytest.fail("not implemented: see docstring")


# ── stream events: one emitter, observed status, declared vocabulary ─────────


@UNWRITTEN
def test_every_emitted_step_name_is_a_declared_stage() -> None:
    """ADR 0007 §5. The closure that keeps the two ends of the timeline from drifting.

    Events are emitted from `serve/wrap.py`, not from the nodes: every node is already
    wrapped, so one emitter covers every stage and cannot drift per node. Twenty hand-placed
    `writer(...)` calls is twenty chances to forget one, and a forgotten call is a step that
    silently never appears — indistinguishable from a stage that did not run.

    Assert every `step` in a turn's events is a member of `register/stages.py`'s `Stage`, and
    that the stages a turn actually ran all appear. The second half is the one that catches a
    missing emitter; the first catches a hand-written label drifting from the register.

    Assert `seq` is strictly increasing: the UI orders by it, so a duplicate reorders the
    timeline and a client cannot tell.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_an_event_status_reports_what_the_node_did() -> None:
    """The same rule that `_channels_for` broke, in a new place — and it is worth stating
    plainly, because this is the third time it has appeared in this system: a status computed
    from configuration makes a broken run and a clean run produce identical artifacts.

    Drive a turn whose governance refuses a statement, and assert the `run_query` event's
    status is `blocked`/`refused` rather than `ok`. Then drive one that succeeds and assert
    `ok`. Without the second half, a server that reports everything as `blocked` passes.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_a_clarification_interrupt_carries_an_id_and_a_reason() -> None:
    """ADR 0007 §6, and the failure it prevents is the worst kind: a **deadlock that looks
    idle**.

    v2 sends `interrupt({"type": "ask_user", "question": ...})`. The UI requires
    `kind: "clarification"` (a `z.literal`), plus `clarification_id` and `why`; on a mismatch
    it drops the interrupt, so the prompt never mounts, `isLoading` is false, the graph waits
    forever, and the interface shows nothing wrong.

    Assert the payload carries all four. `clarification_id` is what makes an answer
    attributable to a question rather than to whatever is pending, and `why` is a real thing
    to record about a clarification — this is a better payload, not merely a conforming one.
    """
    pytest.fail("not implemented: see docstring")
