"""Parcel J's acceptance criterion: the HTTP surface, per ADR 0007.

**Written 2026-08-03, before `src/governed_bi/api/` exists.** ADR 0007 is the design; this
file is what makes it checkable. `tools/check_imports.py` has declared an `api` layer since
before v1 was deleted, and nothing has ever been in it.

**Do not edit this file to make it pass.** If a test looks wrong, stop and say so.

**Every specification here now has a body** (2026-08-11). Seven of the ten were strict-xfail
stubs for the whole of v2, and one cause covered all seven: the surface they describe could not
be constructed. `routes.app` reached a memoised session built from the environment and the
graph factory closed over the same global, so reaching any of this needed a Postgres server, a
corpus and a credential. `routes.make_app(session, turn_log)` and
`graph_app.build_serve_graph(session)` take their dependencies, and the fixtures below are four
assets in memory. Nothing here needs a database, a model or a key.

**`POST /chat` and `POST /chat/resume` are deleted** (2026-08-18, ADR 0014). One specification
here was stated over that transport — the record-on-the-wire and `text`-asymmetry pair — and it is
stated on the served graph's `answer` instead, which *is* the wire now that no shaping layer stands
between the graph and the client. That test says so at length, because the old framing made the
REST boundary the whole point. Nothing else here touched the chat pair; the transport's own
response-shaping tests lived in `tests/serve/test_chat_transport.py` and went with it.

One specification was **deleted rather than moved**: "the audit log can be asked for one
conversation" read `api/trace_store.list_turns` off the repository's own JSONL log, and both the
module and the log are gone — the audit surface reads thread state. Its claim was that the log is
the *only* place a thread's earlier turns survive, which is now the opposite of true, and the
filter it pinned is pinned against the real store in
`tests/api/test_the_audit_surface_reads_thread_state.py`.

Two rules run through all of it, and both are governance rather than plumbing:

1. **A client may not write the run's claims about itself.** `run_id`, `corpus_content_hash`,
   `knobs_resolved` and their siblings are what every quotability gate reads. A
   client-settable provenance field is a forgeable record — the same reason ADR 0006 says no
   tool writes to `licensed`.
2. **A field the engine does not observe must not be invented at the boundary.** v1's
   `AnswerView` required a `tier`, a `safety_clearance` and a `semantic_assurance` on the answer
   card; v2 observes none of the three. Synthesizing one in the server would put a reliability
   claim with nothing behind it on the most prominent badge in the interface, which is the
   defect class the rewrite existed to remove.

   **`tier` is the one of the three that also names something real, and the two must not be
   confused.** `RecordField.tier` off `register/record.py`'s `RECORD_REGISTER` says *why a field
   is recorded* — `identity` | `treatment` | `decision` | `outcome` | `cost` | `health` — and
   `/audit/turns/{id}/trace` serialises it per register row. That is a property of the register,
   not a verdict about an answer, and the client says so in as many words
   (`ui/lib/schemas.ts`'s `auditTraceFieldSchema`). ADR 0007 §3 bans the *reliability* tier and
   says nothing about this one, so the structural test below pins the register site by name and
   fails on a second producer, rather than banning the word.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from contracts import needs  # noqa: E402

pytestmark = [needs("J")]

#: `src/governed_bi`, for the structural assertions. Some of these must be structural: a
#: behavioural test that "the server does not synthesize a tier" passes for every input the
#: test happens to try, and says nothing about the next one.
SRC = Path(__file__).resolve().parent.parent.parent / "src" / "governed_bi"

REPO = Path(__file__).resolve().parent.parent.parent

#: A prompt the four-asset corpus below routes to `beer` on the lexical channel alone.
QUESTION = "how many root beer brands are there"


@pytest.fixture(autouse=True)
def _isolated():
    """The one piece of process-wide state this file touches, cleaned up around every test.

    ``build_serve_graph`` declares its session's constants trusted, and that registry is
    process-wide (``serve/runtime.trust``) — which is the design, since the server is one
    session per process. In a suite it is shared mutable state, and the failure mode is the
    worst kind: a test that passes because an earlier one registered a corpus.
    """
    from governed_bi.serve.runtime import trust

    trust()
    yield
    trust()


class _EchoConnector:
    """A connector double, for the one test whose subject is the *governance verdict*.

    Real enough that a refusal is a refusal: with ``connector=None`` a governed block is a
    wiring failure and proves nothing (``tests/serve/turn_contract_fixtures`` says so at
    length). Nothing here asserts what a database returned.
    """

    dialect = "postgres"

    def execute(self, sql: str, max_rows: int | None = None) -> Any:
        return (["count"], [(3,)], False)


def _served(session: Any) -> Any:
    """The served topology, sync-callable. What ``langgraph.json`` runs.

    ``as_sync`` only because this file's tests are sync ``def``; the platform drives
    ``ainvoke`` itself. The graph is otherwise exactly the process entry's.

    It takes no turn log: ``record`` returns the finished turn onto ``ServeState.turns`` and the
    checkpointer persists it, so there is no sink to inject.
    """
    from governed_bi.api.graph_app import build_serve_graph
    from governed_bi.serve.graph import as_sync

    return as_sync(build_serve_graph(session))


class _TurnLog:
    """Everything ``make_app`` asks of a turn log, in memory. **Readers only.**

    There is no ``append_turn``: the seam is a reader since ADR 0014, because the only writer of a
    turn is ``record_node`` putting it on ``ServeState.turns``. A fake that still accepted writes
    would keep a second sink alive in the tests after it was deleted from the engine.
    """

    TURN_LOG_DIR = Path("/nowhere")
    SUMMARY_FIELDS: tuple[str, ...] = ("turn_id", "outcome")

    def __init__(self, rows: list[dict[str, Any]] | None = None) -> None:
        self.rows: list[dict[str, Any]] = list(rows or ())

    def list_turns(self, limit: int = 50, thread_id: str | None = None) -> list[dict[str, Any]]:
        return [r["record"] for r in self.rows][:limit]

    def get_turn(self, turn_id: str) -> dict[str, Any] | None:
        return next((r for r in self.rows if r["record"].get("turn_id") == turn_id), None)


# ── the record is the run's, not the client's ─────────────────────────────────


def test_a_client_cannot_set_any_provenance_field() -> None:
    """ADR 0007 §2. The most important test here.

    The UI submits one key — `{messages: [{type: "human", content}]}` — and the record
    requires fifteen fields. Something server-side must mint the rest. The failure mode is
    not that it forgets: it is that it **merges** what the client sent.

    `run_id`, `turn_id`, `question_id`, `corpus_content_hash`, `prompt_set_hash`,
    `knobs_resolved` are the run's own claims about itself, and `measure/gates.py` reads them
    to decide whether a run is quotable. A client that can set `corpus_content_hash` can make
    two different corpora report as one, which is a forged comparison rather than a bad one.

    **Fixture shape.** Invoke the graph the way the server does, with a client payload that
    sets every required field to a recognisable sentinel. Assert **no sentinel reaches the
    record** — field by field, from `required_keys()`, not from a hand-written list. Assert
    the turn still succeeds: silently dropping the whole turn would also pass a
    "no sentinel survived" check.

    **Written 2026-08-11**, once `build_serve_graph` existed. It was a stub for the whole of
    v2 because the served topology could only be assembled from a process-wide session built
    out of the environment, so the graph this asserts about could not be constructed in a
    test at all (the 2026-08-11 review, C5).

    Two mechanisms carry the claim and both are exercised here. `ServeInput` drops undeclared
    keys at the entry, so most sentinels never reach a channel; `accept` then *overwrites* the
    turn identity from `Session.turn`, so the ones that are declared channels do not survive
    either. Asserting on the record rather than on either mechanism is deliberate — the record
    is what a gate reads.
    """
    from langchain_core.messages import HumanMessage

    from governed_bi.register.record import record_keys, required_keys

    session = _indexed_session()
    forged = {name: SENTINEL for name in required_keys()}
    assert forged, "precondition: the register declares no required fields"

    out = _served(session).invoke(
        {"messages": [HumanMessage(content=QUESTION)], **forged},
        {"configurable": {"thread_id": "t-forge"}},
    )
    record = out["answer"]["record"]

    survived = sorted(name for name in required_keys() if _mentions(record.get(name)))
    assert not survived, (
        f"{survived} reached the record from the client's payload. Every quotability gate "
        "reads these, so a client-settable one is a forged record rather than a wrong one"
    )
    # Not merely dropped — minted. A turn that silently produced nothing would also have no
    # sentinel in it.
    assert out["answer"]["outcome"] != "crashed", out["answer"]
    assert record["corpus_content_hash"] == session.corpus_content_hash
    assert record["run_id"] == session.run_id
    assert record["turn_id"] and record["turn_id"] != SENTINEL
    assert set(record) == record_keys()


#: Recognisable in any field the register declares, whatever its type.
SENTINEL = "client-forged-sentinel"


def _mentions(value: Any) -> bool:
    """Whether ``value`` carries the sentinel anywhere a client could have put it."""
    if isinstance(value, str):
        return SENTINEL in value
    if isinstance(value, dict):
        return any(_mentions(v) for v in value.values()) or any(_mentions(k) for k in value)
    if isinstance(value, (list, tuple)):
        return any(_mentions(v) for v in value)
    return False


def test_the_graph_is_loadable_the_way_langgraph_json_loads_it() -> None:
    """`langgraph.json` names a factory by file path, and LangGraph Server can only put
    **JSON** in `config.configurable` — while every node needs live objects: `policy` (a
    dataclass, subscripted unguarded at `serve/nodes/guard.py::guard_node`), `agent_model`, `corpus`,
    `index`, `structure`, `connector`, `assets_by_id`.

    So the factory must close over a `Session`. Assert it does: build the graph the way the
    server entry does, invoke it with a `configurable` containing **only JSON**, and assert
    the turn reaches a terminal path. A `KeyError` on `policy` mid-run is the failure this
    catches, and it is the failure that would only appear on the first real request.

    Assert `langgraph.json` itself parses and its `graphs` key names `serve` — that string is
    the UI's `ASSISTANT_ID` default, so a rename silently 404s every chat request.

    **Written 2026-08-11.** The half of this that used to be checked was checked by reading
    `graph_app.py` as text and asserting the substring `"trust("` appeared in `make_graph`'s
    body — which passes for a call that is unreachable or handed the wrong mapping. It was
    written that way because `make_graph` builds a Postgres connector; `build_serve_graph`
    takes the session, so the claim runs.
    """
    import json

    from langchain_core.messages import HumanMessage

    config = json.loads((REPO / "langgraph.json").read_text(encoding="utf-8"))
    assert "serve" in config["graphs"], (
        f"the UI's default ASSISTANT_ID is 'serve'; langgraph.json declares "
        f"{sorted(config['graphs'])}, so every chat request 404s"
    )
    target = config["graphs"]["serve"]
    assert target.endswith(":make_graph") and "api/graph_app.py" in target, target
    assert config["http"]["app"].endswith("api/routes.py:app"), config["http"]["app"]

    # JSON only. Everything a node needs has to come from the closure, not the wire.
    only_json = {"configurable": {"thread_id": "t-json", "checkpoint_ns": ""}}
    out = _served(_indexed_session()).invoke(
        {"messages": [HumanMessage(content=QUESTION)]}, only_json
    )

    answer = out["answer"]
    assert answer["outcome"] != "crashed", (
        "the graph could not run on a JSON-only config, which is the only kind LangGraph "
        f"Server can send: failed_stage={answer['failed_stage']!r} "
        f"error_type={answer['error_type']!r}"
    )
    assert answer["record"]["licensed"], "nothing was licensed, so no node reached the corpus"


# ── /capabilities: observations, and false is a real answer ───────────────────


def test_capabilities_reports_what_is_true_not_what_is_configured() -> None:
    """It is the UI's **first** request; without it the chat panel pins at a skeleton
    forever, so this route failing is indistinguishable from the whole backend being down.

    `has_live_model` must be false when no model is configured, and `can_clarify` false when
    the `ask_user` tool is not bound. Assert the false cases, because the true ones pass for
    a server that hard-codes `true` — and a hard-coded `has_live_model` is the stub-path
    defect again, one layer out: the interface would promise a model that will never answer.

    `can_edit` is **false** for now: the curator is out of scope, and reporting it true would
    put an edit button in front of a route that does not exist.

    **Both directions, over the real route.** Two apps differing only in whether the session
    carries a model: a hard-coded `true` fails the first and a hard-coded `false` fails the
    second, so neither reading of the field can pass by accident. Reachable at all only since
    `make_app` — the route used to resolve its session from the environment.
    """
    from governed_bi.api.routes import make_app

    modelless = _client(make_app(_indexed_session(), _TurnLog())).get("/capabilities")
    assert modelless.status_code == 200, modelless.text
    caps = modelless.json()
    assert caps["has_live_model"] is False, (
        "the interface was promised a model that will never answer"
    )
    assert caps["can_clarify"] is False, (
        "the clarification prompt mounts on a turn that can never raise one, and a turn that "
        "looks idle while nothing is pending is the deadlock ADR 0007 §6 is written against"
    )
    assert caps["can_edit"] is False and caps["edit_mode"] == "none"
    assert caps["can_search"] is False, "there is no /search route; false is the true answer"

    with_model = _client(
        make_app(_indexed_session(model=object()), _TurnLog())
    ).get("/capabilities")
    assert with_model.json()["has_live_model"] is True, (
        "a configured model is reported absent, so the panel degrades on a server that works"
    )
    assert with_model.json()["can_clarify"] is True


def _client(app: Any) -> Any:
    """A ``TestClient`` over ``app``. No credential: the engine requires none (2026-08-13)."""
    from fastapi.testclient import TestClient

    return TestClient(app)


def _indexed_session(*, model: Any = None, connector: Any = None, policy: Any = None) -> Any:
    """Four assets over one schema, with a real index and structure.

    Small, and large enough to route: the term and the table both mention "root beer", so
    :data:`QUESTION` reaches ``beer`` on the lexical channel with no embedder. Built through
    ``from_assets`` rather than by hand, so the index, the structure and ``assets_by_id`` are
    the ones a real corpus produces.
    """
    from governed_bi.corpus.schema import (
        AssetType,
        Binding,
        ColumnAsset,
        SchemaAsset,
        TableAsset,
        TermAsset,
    )
    from governed_bi.govern.policy import GovernancePolicy
    from governed_bi.serve.session import from_assets

    assets = [
        SchemaAsset(id="beer", name="beer", summary="beer brands and sales"),
        TableAsset(
            id="beer.brands", schema="beer", physical_name="brands",
            summary="Brands of root beer.", columns=("beer.brands.name",),
        ),
        ColumnAsset(
            id="beer.brands.name", schema="beer", parent_table="beer.brands",
            physical_name="name", summary="Brand name.",
        ),
        TermAsset(
            id="term.root_beer", name="root beer", summary="root beer, sarsaparilla",
            binding=Binding(target_type=AssetType.column, target_id="beer.brands.name"),
        ),
    ]
    session = from_assets(
        assets,
        connector=connector,
        policy=policy or GovernancePolicy(guard_rules_enabled={}),
        db_id="beer",
        corpus_content_hash_="corpus-under-test",
        agent_model=model,
    )
    assert not session.fatal_problems, [str(p) for p in session.fatal_problems]
    return session


def _tiny_session() -> Any:
    """One table, one column, one term bound to that column. No model, no connector.

    Small on purpose: every assertion below is about a *shape*, and a shape is easier to
    read wrong in a large fixture than in a small one.
    """
    from governed_bi.corpus.schema import AssetType, Binding, ColumnAsset, TableAsset, TermAsset
    from governed_bi.govern.policy import GovernancePolicy
    from governed_bi.retrieve.structure import CorpusStructure
    from governed_bi.serve.session import Session

    table = TableAsset(id="beer.brands", schema="beer", physical_name="brands", summary="Brands.")
    column = ColumnAsset(
        id="beer.brands.name",
        schema="beer",
        parent_table="beer.brands",
        physical_name="name",
        summary="Brand name.",
    )
    term = TermAsset(
        id="term.root_beer",
        name="root beer",
        summary="root beer, sarsaparilla",
        binding=Binding(target_type=AssetType.column, target_id="beer.brands.name"),
    )
    by_id = {a.id: a for a in (table, column, term)}
    structure = CorpusStructure(
        join_edges=frozenset(),
        references={
            "beer.brands": frozenset({"beer.brands.name"}),
            "beer.brands.name": frozenset({"beer.brands"}),
            "term.root_beer": frozenset({"beer.brands.name"}),
        },
        asset_types={a.id: a.asset_type.value for a in (table, column, term)},
        table_schemas={"beer.brands": "beer"},
        schema_tags={"beer.brands": "beer", "beer.brands.name": "beer", "term.root_beer": "beer"},
        joins_by_edge={},
    )
    return Session(
        index=None,
        structure=structure,
        assets_by_id=by_id,
        corpus=None,
        connector=None,
        policy=GovernancePolicy(guard_rules_enabled={}),
        corpus_content_hash="c",
        prompt_set_hash="p",
        knobs_resolved={},
        db_id="beer",
        run_id="r",
    )


#: The client's `graphNodeKindSchema`, read out of `ui/lib/schemas.ts` — not a copy of it. It was
#: a hand-typed copy while the UI was a sibling repository a test could not assume was checked
#: out; it is in this tree now, and the direction a copy cannot see is the one that matters, since
#: the assertion is server ⊆ client and a kind *removed* on the client silently widens what
#: passes. A regex, not a TS parse: needing a JS toolchain to run `pytest` is the worse trade, and
#: an empty parse raises rather than leaving that `<=` vacuous. **Sensitive only to the kinds the
#: fixture emits** — mutation-verified both ways, deleting `"term"` fails the assertion below and
#: deleting `"note"` does not, because `_tiny_session()` produces `table` and `term` and no more.
CLIENT_SCHEMAS_TS = Path(__file__).resolve().parent.parent.parent / "ui" / "lib" / "schemas.ts"
_PATTERN = r"graphNodeKindSchema\s*=\s*z\.enum\(\[(.*?)\]\)"
_ENUM = re.search(_PATTERN, CLIENT_SCHEMAS_TS.read_text(encoding="utf-8"), re.DOTALL)
assert _ENUM, f"graphNodeKindSchema not found in {CLIENT_SCHEMAS_TS}"
CLIENT_GRAPH_NODE_KINDS = frozenset(re.findall(r'"([^"]+)"', _ENUM.group(1)))
assert CLIENT_GRAPH_NODE_KINDS, f"graphNodeKindSchema is an empty enum in {CLIENT_SCHEMAS_TS}"


def test_the_pages_that_do_not_need_a_model_work_without_one() -> None:
    """`/audit/corpus`, `/schema/summary`, `/corpus/assets`, `/graph` and `/knowledge-graph`
    are **ungated** in the UI — nothing checks a capability before calling them, so a 500 from
    any of them is a broken page rather than a degraded one.

    All five are projections of the `Session`'s assets and, now that `CorpusStructure`
    exists, the two graph routes are edges plus assets rather than new work. None needs a
    model or an API key.

    Assert they answer on a session built with **no** `agent_model`. This is what makes the
    corpus browsable before anyone has paid for a single token.

    (`/schema` — the flat dump — was on this list and is **deleted**, so the list names
    `/schema/summary` instead. That is the same page: the dump was a second projection of
    these tables, and the catalog is the one that survived. The route is asserted absent
    below, because a deleted route that quietly comes back is two shapes again.

    `/health` was on it too, and is deleted for the same reason one layer up: it and
    `/audit/corpus` projected the same session fields, and the one that survived is the one
    that keeps `fatal` and `degradations` apart. It is asserted absent beside `/schema`.)

    **And that answering is not enough.** Every one of these five is `safeParse`d by the
    client, which throws on a mismatch — so a 200 carrying an undeclared `kind` is the same
    broken page as a 500, reached by a route no server-side test was watching. That is not
    hypothetical: `/knowledge-graph` returned 200 with 107 `kind: "column"` nodes and the
    Semantic graph tab rendered `0 of 0 shown`. So the node vocabulary is asserted too.
    """
    from governed_bi.api.routes import make_app

    # An app over this session, rather than the process one with two private functions swapped
    # out. `make_app` is why: before it, `routes.app` reached `session_from_environment` and
    # `browse_routes` imported `routes` backwards to reach the same global, so a test had to
    # patch both — and patching the second was the only thing that made the browse routes
    # answer at all.
    app = make_app(_tiny_session(), _TurnLog())
    client = _client(app)

    for path in ("/audit/corpus", "/schema/summary", "/corpus/assets", "/graph", "/knowledge-graph"):
        response = client.get(path)
        assert response.status_code == 200, f"{path} -> {response.status_code} with no model"

    # Every deletion, asserted on the app's own route table rather than by fetching them:
    # `/schema/{table_id}` would answer `GET /schema` with a 404 either way, so a status check
    # cannot tell "deleted" from "a table happens not to be named that".
    #
    # **This sweep sees only routes declared directly on the app, and that is audit M7, still
    # open.** On fastapi 0.141 `include_router` collapses the whole browse router into a single
    # `_IncludedRouter` whose `path` is `None`, so `/schema/summary`, `/schema/{table_id}` and
    # `/columns/{id}/related` are not in `app.routes` at all. The assertions below therefore
    # cannot fail for a `/schema` re-added to `make_router` — only for one re-added to
    # `_build_app`. `api/routes.py`'s middleware note records the same `_IncludedRouter`
    # behaviour, from the other side. The chat pair *was* declared on `_build_app`, so that one
    # this does see.
    declared = {getattr(route, "path", None) for route in app.routes}
    assert "/schema" not in declared, (
        "GET /schema is deleted: it was 936 KB inlining every column of every table, and a "
        "second projection of what /schema/summary returns lean"
    )
    assert "/health" not in declared, (
        "GET /health is deleted: /audit/corpus answers the same question from the same session "
        "fields and keeps fatal apart from degradations, which ADR 0008 D9 requires. /livez is "
        "the liveness probe and does not touch the session"
    )
    assert not declared & {"/chat", "/chat/resume"}, (
        "POST /chat and POST /chat/resume are deleted (ADR 0014). They were a second serve "
        "topology with a checkpointer of their own, so the two transports never shared a thread "
        "and degrading to REST lost the conversation. A route re-added here is that second store "
        "back, and the audit surface would have a second writer again"
    )

    graph = client.get("/knowledge-graph").json()
    kinds = {node["kind"] for node in graph["nodes"]}
    assert kinds, "the semantic graph drew nothing at all"
    assert kinds <= CLIENT_GRAPH_NODE_KINDS, (
        f"{sorted(kinds - CLIENT_GRAPH_NODE_KINDS)} is outside the client's node vocabulary; "
        "the client rejects the whole response, so this is a blank tab, not a missing node"
    )

    # Every endpoint must be a node that exists. Columns are re-pointed to their table, and a
    # re-point that lands nowhere is a dangling edge the client renders as an invisible line.
    ids = {node["id"] for node in graph["nodes"]}
    dangling = [e["id"] for e in graph["edges"] if e["source"] not in ids or e["target"] not in ids]
    assert not dangling, f"edges with no node at one end: {dangling}"

    # The term is bound to a *column*; re-pointing must keep it attached to the column's table
    # rather than stranding it, which is the whole reason columns are re-pointed and not dropped.
    assert ("term.root_beer", "beer.brands") in {(e["source"], e["target"]) for e in graph["edges"]}, (
        "a term bound to a column lost its edge when the column stopped being a node"
    )


def test_capabilities_reports_the_ported_utkuai_toggles(monkeypatch) -> None:
    """enable_structured_percentage_check / enable_clarification_to_draft are UtkuAI additions
    (utku-ai-v2-porting-spec.md), not part of upstream's own capabilities contract above --
    read off session.knobs_resolved the same way `model`/`llm_model` already is, so a
    deployment override is reflected here rather than a second hard-coded default."""
    from fastapi.testclient import TestClient

    from governed_bi.api import routes

    session = _tiny_session()
    client = TestClient(routes.make_app(session, _TurnLog()))

    caps = client.get("/capabilities").json()
    assert caps["enable_structured_percentage_check"] is False  # register default
    assert caps["enable_clarification_to_draft"] is False  # register default

    # The same app, and the override reaches it: `capabilities_for` reads `knobs_resolved` per
    # request, so this asserts the value is not captured once at construction.
    session.knobs_resolved["enable_structured_percentage_check"] = True
    session.knobs_resolved["enable_clarification_to_draft"] = True
    caps = client.get("/capabilities").json()
    assert caps["enable_structured_percentage_check"] is True
    assert caps["enable_clarification_to_draft"] is True


def test_capabilities_reports_can_curate_corpus_from_corpus_root(monkeypatch, tmp_path: Path) -> None:
    """`can_curate_corpus` (Phase 5) is a separate question from `can_clarify`: `can_clarify`
    is "does a live `ask_user` interrupt fire", `can_curate_corpus` is "would
    `/corpus/conflicts*`, `/corpus/assumptions`, and `/corpus/drafts/{id}/approve` actually
    work for this session". Mirrors `approve_draft_route`'s own precondition exactly
    (`session.corpus_root is None` -> 409), so the two flags cannot be conflated again."""
    from dataclasses import replace

    from fastapi.testclient import TestClient

    from governed_bi.api import routes

    session = _tiny_session()
    caps = TestClient(routes.make_app(session, _TurnLog())).get("/capabilities").json()
    assert caps["can_curate_corpus"] is False  # _tiny_session has no corpus_root

    # A second app rather than a re-patched global: `make_app` takes the session, so "the same
    # server with a corpus root" is a different app, not a mutated module.
    with_root = routes.make_app(replace(session, corpus_root=tmp_path), _TurnLog())
    caps = TestClient(with_root).get("/capabilities").json()
    assert caps["can_curate_corpus"] is True
