"""The session and the entry point: ADR 0005 §2.8.2.2's acceptance criterion.

**Written 2026-08-03, before either exists.** This is the walking skeleton — the piece that
turns "the tests are green" into "a real question was answered by a real model against a
real database, and the record of it is complete."

That distinction is the reason this file is worth its length. At the time of writing the
suite is 346 green with nine defects fixed, and **not one real question has ever been
served**: every piece of evidence comes from a contract test or a `ScriptedChatModel`. A
skeleton that printed a plausible answer and said nothing checkable about the record would
convert that gap into confidence without closing it.

**Do not edit this file to make it pass.** If a test looks wrong, stop and say so.

The seam under all of it: **run-constant versus per-turn.** `index`, `structure`, the
corpus, the connector, the policy, the model, the resolved knobs and the two hashes are
constant for every turn of a run. The five deleted "optional wiring hooks" put data of
exactly that kind into per-turn state, and that is a place where two turns of one run can
disagree — which is how every retired number in this project was produced.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))
from turn_contract_fixtures import dsn, probe  # noqa: E402, F401 -- pytest fixtures, by name

from contracts import needs  # noqa: E402

#: A specification with no body. Per test, never module-level.
UNWRITTEN = pytest.mark.xfail(strict=True, reason="contract specified, body not yet written")

pytestmark = [needs("F")]


# ── the session is the only way to wire a turn ────────────────────────────────


@UNWRITTEN
def test_a_session_configurable_is_sufficient_to_serve(probe) -> None:  # noqa: F811
    """The interface claim: `Session.configurable()` and `Session.turn(question)` are
    **enough**, with nothing assembled by the caller.

    Today a caller hand-builds eight `configurable` keys and a fourteen-key turn dict, and
    the only two places that do it correctly are `eval/harness.py` and a test fixture. A
    node handed a half-wired config does not fail loudly — it degrades: no `index` means no
    retrieval, no `agent_model` means the stub, and both look like an answer.

    Assert `compile_graph().invoke(session.turn(q), session.configurable())` reaches a
    terminal path, and that **`missing_required(record)` is empty**. Do not add keys to
    either mapping in the test: if something is missing, the session is wrong, and patching
    it here would hide exactly the defect this asserts against.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_the_session_carries_no_per_turn_information(probe) -> None:  # noqa: F811
    """The seam, asserted rather than described.

    Two turns of one session must see **identical** run constants: the same `index`, the
    same `structure`, the same `corpus_content_hash`, the same resolved knobs. Assert
    `configurable()` is equal across two calls, and that the two turns' records agree on
    every one of those fields.

    Then assert the complement, which is what makes this test more than a tautology: the two
    turns' `question_id`, `turn_id` and `context_hash` **differ**. A session that returned
    one frozen turn would satisfy the first half perfectly.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_index_entries_and_edges_resolve_a_join_to_the_same_schema(probe) -> None:  # noqa: F811
    """One resolution, two outputs — the defect that would otherwise be silent.

    A `JoinAsset`'s index `schema_tag` is *`left_table`'s schema* (§2.2), and `left_table` is
    a physical name needing the same reconciliation §2.8.2 specifies for edge endpoints. Two
    independent resolutions can disagree, and **nothing raises**: the join votes for one
    schema in routing while connecting two tables in another.

    Assert that for every join in the index, its `schema_tag` is the schema of the table its
    edge's left endpoint names. Assert it over the **seeded probe corpus**, which has a real
    foreign key, rather than a hand-built pair — the two mappings agree trivially on a
    fixture built by one hand.
    """
    pytest.fail("not implemented: see docstring")


# ── the corpus enters from two places, and both are real ─────────────────────


@UNWRITTEN
def test_both_corpus_sources_produce_a_servable_session(tmp_path, probe) -> None:  # noqa: F811
    """One adapter is a hypothetical seam. Two make it real.

    `store.load(root)` for the curated corpus and `seed(connector.introspect(schema),
    schema)` for a live schema. `Session` must not know which it got.

    **Fixture shape.** Seed from the live probe schema, write those assets out with
    `store.write` into `tmp_path`, load them back, and assert the two sessions serve the
    same question to the same `corpus_content_hash`. That round-trip is the assertion:
    it catches a `store` that drops a field on write or on read, which is v1's loader
    failure in the direction that does not raise.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_a_corpus_problem_reaches_a_caller_that_can_fail(tmp_path) -> None:
    """§2.8.2's own requirement, which nothing could satisfy until there was an entry point.

    Both sources return `problems`, the builder returns them, `Session` carries them — and
    every one of those hand-offs is worthless if the last caller drops them. That is exactly
    what happens today: the serve-time fallback records an unresolvable join endpoint and
    discards it.

    **Fixture shape.** Write a corpus containing one asset that `problems_with` rejects and
    one join whose endpoint cannot be resolved — two different classes, because a caller
    that reports only load problems looks identical to one that reports everything until a
    projection problem appears.

    Assert the problems are **carried on the session**, and that the entry point **exits
    non-zero** rather than serving. A warning printed to stderr while serving anyway is the
    silent-skip shape: it satisfies "we reported it" and changes no outcome.
    """
    pytest.fail("not implemented: see docstring")


# ── the entry point exists to make the record checkable ──────────────────────


@UNWRITTEN
def test_the_entry_point_exits_non_zero_on_an_incomplete_record(probe) -> None:  # noqa: F811
    """Why this is a skeleton and not a demo.

    `python -m governed_bi.serve` must exit non-zero when `missing_required(record)` is
    non-empty, and it must **name the missing fields**. An entry point that prints an answer
    and exits 0 is indistinguishable from one that works, which is the entire failure mode
    this repository keeps rediscovering: `STUB_ANSWER` reaching an artifact, `ex=1.00` from
    zero executions, a degradation gate passing with no index.

    Assert both directions. A complete turn exits 0; a turn deprived of a required field
    exits non-zero with that field named. Drive it as a subprocess so the exit code is the
    real one, not a `SystemExit` a test caught.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_the_resolved_knobs_name_the_model_that_answered(probe) -> None:  # noqa: F811
    """`llm_model` becomes a knob here, and it does not exist yet.

    `knobs.py` declares `llm_temperature`, `llm_reasoning_effort` and `embedding_model` as
    `Role.comparability`, and its own docstring condemns model identity going unrecorded —
    yet the chat model itself is not a knob. So two runs on different models compare as one
    experiment: v1's incident with the variable changed, and that one moved a baseline arm
    **+2.5pp against a 2.3pp detection threshold**.

    The session chooses the model, so the session resolves the knob. Assert `knobs_resolved`
    names it, that it reaches the record, and that changing the model **changes the serve
    config hash** — a knob that does not move the hash is a knob nothing compares.

    This is also what unblocks decision #45(a): the `usage` gate condition compares every
    usage row's model against this knob, which is what makes a silent fallback to the stub
    path — or to a different model — a failed gate rather than an ordinary run.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_a_real_model_answers_a_real_question_over_a_real_database(probe) -> None:  # noqa: F811
    """The one assertion this whole parcel exists to make, and it needs a paid call.

    Everything else in the suite is a contract test or a `ScriptedChatModel`. This drives a
    real chat model, a real BM25 index over a real seeded corpus, and a real
    `PostgresConnector` — and asserts the record.

    **Skip loudly without credentials**, naming the environment variable and never printing
    its value; a silent skip here is a suite that reports the skeleton works when nothing
    ever called a model. Keep it to **one question and one cheap model**: a test whose cost
    scales with anything will be switched off, and a switched-off test is how v1's gates
    ended up unread.

    Assert: `outcome == "answered"`, `missing_required(record)` empty, at least one ledger
    attempt with `passed is True`, `STUB_ANSWER` absent, and `usage` carrying **measured**
    token counts — a real provider reports them, so an unmeasured count here means the
    usage plumbing is reading the wrong place.
    """
    pytest.fail("not implemented: see docstring")


def test_two_threads_asking_one_question_are_two_turns(two_schema_assets, guard_off_policy):
    """``turn_id`` must separate conversations, or the audit log loses one of them.

    It digested ``(run_id, turn_index, question)`` and not the thread, so two conversations
    asking the same question in one run minted the **same** id. The turn log keys on it, so
    the turn reader returned the first and the second turn was simply unreachable in
    the trace view — and React refused to render the list at all, because two rows carried one
    key. Observed live: "how many air carriers are listed?" at 04:39 and again at 05:52.

    The pair matters as much as the difference: a *resumed* turn has to keep its identity, so
    the id is still a digest and not a random value. Same thread, same index, same question →
    same id.
    """
    from governed_bi.serve.session import from_assets

    session = from_assets(
        list(two_schema_assets.values()),
        connector=None,
        policy=guard_off_policy,
        db_id="ops_b",
        corpus_content_hash_="c",
        agent_model=None,
    )
    question = "how many air carriers are listed?"
    a = session.turn(question, thread_id="thread-a")
    b = session.turn(question, thread_id="thread-b")
    assert a["turn_id"] != b["turn_id"], (
        "two conversations asking one question produced one turn_id; the audit log keys on it"
    )
    again = session.turn(question, thread_id="thread-a")
    assert again["turn_id"] == a["turn_id"], (
        "the id must stay a digest of the thread and the turn -- a resumed turn keeps its "
        "identity, which is why this is not simply randomised"
    )
    # `question_id` is deliberately the opposite: it digests the question *text* so the same
    # question is recognisable across threads, which is what makes a re-serve visible.
    assert a["question_id"] == b["question_id"]
