"""Parcel F's acceptance criterion: what a served turn must record about itself.

**Written 2026-08-03, after `serve/` had already been implemented and self-graded.** That
ordering is a departure and it is the reason this file is blunt: every test below encodes
a defect an adversarial review found in the existing code, reproduced by execution. A
contract written before implementation prevents; this one convicts.

**Do not edit this file to make it pass.** If a test looks wrong, stop and say so.

The through-line is one rule that `serve/` broke in four places: **the record must
describe what happened, not what was supposed to happen.** Every v1 number this project
retired died of the same thing — a field that reported the configuration rather than the
observation, so a broken run and a clean run produced identical artifacts.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from contracts import needs  # noqa: E402

#: Every test here is a **specification with no body yet**, so each is a strict xfail.
#:
#: Two reasons for the marker rather than a red suite or a deletion. A red suite gets
#: ignored, and this repository already has evidence of what happens next. And
#: ``strict=True`` means the moment someone writes a real body that passes, the suite
#: **fails** until they remove the marker -- so a spec cannot quietly become a test that
#: nobody checked, and it cannot be forgotten either. The same device carried the
#: original "a real turn writes every required field" assertion; what went wrong there
#: was that the marker was removed and the body replaced with a stub, which is the
#: defect this file's first test now convicts.
#:
#: These are NOT for an implementer to strip. Filling one in means writing the assertion
#: the docstring specifies, then deleting that one marker.
pytestmark = [needs("F"), pytest.mark.xfail(strict=True, reason="contract specified, body not yet written")]


# ── the outcome must not contradict the ledger ────────────────────────────────


def test_a_turn_whose_every_sql_attempt_was_refused_is_not_answered() -> None:
    """The finding that invalidates every number `serve/` can produce.

    Observed in the existing implementation: `run_query` refused with
    `r_table_not_licensed`, no statement ever reached the database, and the record read

        outcome: answered
        execution: {"attempts": [{"passed": false, ...}], "terminal": "answered"}

    `has_sql` was derived from the tool-call *arguments*, so producing a string counted as
    producing an answer. A governed refusal recorded as an answer is the crash-counted-as-
    refusal inversion that retired the pre-2026-07-25 numbers, pointing the other way.

    Build a turn where the model emits SQL the corpus does not license. Assert the
    outcome is a refusal or a decline, and that no attempt in the ledger says `passed`.
    """
    pytest.fail("not implemented: see docstring")


def test_execution_terminal_agrees_with_the_attempts_it_carries() -> None:
    """`terminal: "answered"` beside `passed: false` is a record that disagrees with
    itself. Whichever field a reader trusts, the other one is lying, and nothing in the
    artifact says which."""
    pytest.fail("not implemented: see docstring")


# ── channel state must be observed, not declared ──────────────────────────────


def test_a_facet_with_no_index_reports_its_channel_as_failed() -> None:
    """The degradation gate's entire input, and it was inert.

    `_channels_for` returned `expected_channel_state(...)` verbatim, so a facet node run
    with **no index and no model** reported `{'lexical': 'ran', 'semantic': 'ran'}`. The
    field was present and described the configuration.

    `register/facets.py` already draws the distinction this needs: `ran` /
    `not_configured` / `failed`, three-valued precisely so "should have run and did not"
    is expressible. A facet that could not consult an index has a **failed** lexical
    channel, and saying `ran` is the rate-limited-embedder incident reproduced with the
    field in place.
    """
    pytest.fail("not implemented: see docstring")


def test_a_degraded_channel_writes_facet_degraded() -> None:
    """`channel_anomaly` and `is_degraded` had **zero call sites outside tests**, and
    nothing anywhere wrote `facet_degraded` — so `measure/gates.py` passed vacuously:
    `[pass] facet_channels 0.0000 over 'stub' n=3 (fan-out ran)` on an arm with no index.

    A gate whose input nobody produces is worse than an absent gate, because the summary
    says the run was checked.
    """
    pytest.fail("not implemented: see docstring")


def test_pass_two_does_not_score_a_facet_on_a_channel_it_does_not_declare() -> None:
    """`pass_two_retrieve` lacked the `Channel.lexical in FACET_CHANNELS[stage]` guard
    that `facets.py` has, so a few-shot outranked an entity hit on `lexical` — while the
    same turn's record declared `facet_example`'s lexical channel `not_configured`.

    ADR 0005 §2 is explicit that `register/facets.py` decides which channels a facet
    uses and `retrieve/` must never decide it locally. This is `Anomaly.extra_channel`,
    and it went undetected because nothing compares observation to declaration.
    """
    pytest.fail("not implemented: see docstring")


# ── absence must not be invented into a value ─────────────────────────────────


def test_an_absent_guard_is_not_recorded_as_error_failed_open() -> None:
    """`stamp.py` substituted `{"outcome": "error_failed_open"}` for a missing `guard`.

    That sentinel means *the guard ran, errored, and let the question through* — and
    `register/record.py` gates on it. Inventing it for a guard that **never ran** fabricates
    a security event, and the quotability gate then refuses a run for a reason that did
    not happen. L-R1 with the sign flipped: absence became a specific, alarming value
    rather than zero.
    """
    pytest.fail("not implemented: see docstring")


def test_a_real_model_call_does_not_record_zero_tokens() -> None:
    """Observed: `usage: [{'model': 'scripted', 'input_tokens': 0, 'output_tokens': 0}]`
    from a turn that really called a model.

    A **measured** zero, not `not_measured`. `measure/price.py` will price it as free,
    which is precisely the v1 failure of two ladders that produced no USD while reporting
    successfully. If the provider reports no usage, the field is
    `Measured.unmeasured(why)`; `register/quantity.py` exists for this.
    """
    pytest.fail("not implemented: see docstring")


def test_an_absent_corpus_raises_rather_than_defaulting_to_an_empty_one() -> None:
    """G1 — *absence refuses* — in the one place production breached it.

    `tools.py` coerced a wrong-typed corpus to `None` and then defaulted `None` to
    `analyst_corpus_from_keys(allowed=())`. It fails closed, so nothing leaks. But it
    records "the corpus was never wired up" as `r_column_not_allowed` with
    `guardrail_errors: 0` — indistinguishable from "the model asked for a column it may
    not see."

    Production `check()` already raises `GovernanceUsageError` here. `serve/` must not
    catch that and substitute a default; a wiring failure is a crash, not a refusal.
    """
    pytest.fail("not implemented: see docstring")


# ── the end-to-end assertion, and it must not use the stub ────────────────────


def test_a_real_turn_writes_every_required_field_on_every_terminal_path() -> None:
    """The assertion this parcel exists for. Its predecessor was `xfail(strict=True)`;
    the replacement passes through `_stub()`.

    `agent_core_node` falls through to `_stub()` whenever `agent_model` is None, returning
    the literal `STUB_ANSWER`. The replacement test supplied only `thread_id` and
    `policy`, so it ran with no model, no index, no connector, `generated_sql: None`,
    `(no context)`, and route hits **injected** via `facet_route_hits` — bypassing
    retrieval as well. Its name asserted "a real turn."

    That is verbatim what the xfail's own docstring warned of: *"its presence test ran
    against fixtures, so it never met the case that matters."* The fixtures were replaced
    with a stub.

    So this test must assert its own preconditions before asserting anything else: a
    model that emits a tool call, a real index built from a real seeded corpus, a real
    connector, and **no** `facet_route_hits` in the config. Then
    `missing_required(record) == frozenset()` on each of refuse / decline / answered.
    """
    pytest.fail("not implemented: see docstring")


def test_the_stub_path_is_unreachable_when_a_model_is_configured() -> None:
    """The complement, and the reason the test above can be trusted.

    `STUB_ANSWER` reaching an artifact means the graph silently degraded to a path with
    no model. It must be impossible to produce it while a model is configured, and it
    must never appear in a record that any gate reads as `answered`.
    """
    pytest.fail("not implemented: see docstring")
