"""The corpus structure projection: ADR 0005 §2.8.2's acceptance criterion.

**Written 2026-08-03, before the module exists** — the opposite ordering from parcel F's
contract, and the reason this one can prevent rather than convict.

It exists because of what F's contract found by execution. `serve/state.py` declares five
inputs that `resolve` and `connect` read — `join_edges`, `references`, `asset_types`,
`table_schemas`, `schema_tags` — under the comment "F1 test / wiring hooks (optional)", and
**not one of them is written anywhere**: not in `src/`, not in `tests/`, not by the eval
harness. So `connect` has run on an empty edge set on every turn this system has ever
served, and declines `missing_join_path` the moment a turn licenses two tables. Single-table
turns answer. That is why a green suite and a live eval both missed it.

**A note on where this sits.** The projection belongs in `retrieve/`, which is parcel E, and
E is in `ACCEPTED`. E's sign-off was given against scoring, fusion, routing and closure — it
did not cover this module, which did not exist. `tests/contracts.py` tracks acceptance per
*package*, so it cannot say "E accepted, this module not"; this file is separate and strictly
marked so the distinction survives that limitation rather than being absorbed by it.

**Do not edit this file to make it pass.** If a test looks wrong, stop and say so.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from contracts import needs  # noqa: E402

#: A specification with no body. Per test, never module-level: held at module level, one
#: deletion disarms every tripwire at once, and deleting it is what the first passing fix
#: forces. See ``tests/serve/test_turn_contract.py`` for the incident that established this.
UNWRITTEN = pytest.mark.xfail(strict=True, reason="contract specified, body not yet written")

pytestmark = [needs("E")]


# ── node identity: the reconciliation, and it must never guess ─────────────────


@UNWRITTEN
def test_an_ambiguous_endpoint_is_dropped_and_recorded() -> None:
    """The case where a guess fails **open**, which is why guessing is prohibited.

    `connect`'s nodes are asset ids (`{schema}.{physical}`), because they must match the
    identifiers in `licensed`. `JoinAsset` carries `left_table` / `right_table` as physical
    names, **bare or qualified** — `corpus/validate.py`'s `_bare()` accepts both and the ADR
    explicitly declines to settle which. So binding an edge is a lookup, and the lookup can
    find two answers.

    One physical name in two schemas is the *normal* shape of a pooled lake, not a corner
    case. Resolving it by first-match or left-most would license a table in the wrong schema
    and account `crossings` against the wrong pair — a licensing leak, not a lost edge.

    So: the edge is dropped, **and a problem is recorded**. Dropping alone fails closed but
    silently, and the failure then surfaces three layers away as `missing_join_path` on a
    turn that looked ordinary.

    **Fixture shape.** Two `SchemaAsset`s, each with a `TableAsset` whose `physical_name` is
    `customers` — ids `sales_a.customers` and `ops_b.customers`. One `JoinAsset` with
    `left_table="customers"` (bare, ambiguous) and a `right_table` that resolves cleanly.
    Mint the join's id with `join_id` (`corpus/identity.py:151`) so the asset is well-formed
    by the rules `problems_with` already enforces — an edge dropped for being *invalid* would
    prove nothing about an edge dropped for being *ambiguous*.

    Assert both halves. The edge is absent from the projection, and the returned problems
    name that join's id. Asserting only the first is satisfied by a projection that drops
    every edge.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_an_ambiguous_endpoint_does_not_bind_to_either_candidate() -> None:
    """The previous test's assertion stated in the form that catches the tempting fix.

    "Ambiguous endpoints are dropped" is satisfiable by code that drops the *second* match
    and keeps the first, if the problem is recorded anyway. That is precisely the fail-open
    behaviour, with a log line.

    So assert the absence of **both** candidate edges by name, not the count of edges: no
    edge incident to `sales_a.customers`, and none incident to `ops_b.customers`, from that
    join. A count assertion passes if one edge was dropped and a different one invented.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_a_bare_and_a_qualified_endpoint_produce_the_same_edge() -> None:
    """The control, and without it every test above is satisfied by dropping everything.

    `validate.py` accepts `customers` and `sales_a.customers` as the same identifier, so a
    corpus containing both forms is valid and both must bind — to the *same* edge, with
    asset-id endpoints. Two `JoinAsset`s that differ only in the qualification of an endpoint
    are the same relationship: `join_id` already digests the ON clause for exactly this
    reason, and §1.2 records that collapsing two relationships between one table pair cost
    33 of 57 schemas an edge.

    **Fixture shape.** One schema, `customers` and `orders`, and two joins whose `on` is the
    same clause with the operands written in the other order — `on_digest` normalises that,
    so they must mint the same `join_id`, and the projection must not report a problem for
    the duplicate.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_the_edge_endpoints_are_asset_ids_and_not_physical_names() -> None:
    """The namespace assertion, stated on its own because nothing else in the system does.

    `retrieve/connect.py` compares edge endpoints against `terminals` by identity, and
    `terminals` comes from `licensed` / `by_type["table"]` — asset ids. An edge carrying
    `("customers", "orders")` is not wrong-looking anywhere: `_adjacency` builds happily,
    `_canon_edge` canonicalises happily, and `connect` then reports every terminal missing
    and declines. The two namespaces never meet, so nothing raises.

    Assert the endpoints are the ids, `{schema}.{physical}`. And use `table_id` to say so —
    ADR 0005 §2.8.2 requires it to become a declared function beside `derive_column_id` and
    `join_id`, because this reconciliation is the one place a second hand-written copy of the
    convention would silently mis-license a table.
    """
    pytest.fail("not implemented: see docstring")


# ── the projection is a function of the corpus, not of a turn ─────────────────


@UNWRITTEN
def test_the_projection_depends_on_nothing_but_the_asset_set() -> None:
    """Why this is built once beside the index rather than per turn.

    §2.2 already settled the same question for schema tags — *"computed at build, not query
    time"*. The argument is not that recomputing is wasteful. It is that a per-turn
    derivation is a place where **two turns can disagree about the shape of the corpus**, and
    a run whose turns disagree cannot be compared to anything, which is how v1's numbers
    died.

    Assert the projection is a pure function: the same assets in a different order produce an
    equal structure, and building twice produces equal structures. If a signature ever needs
    a question, a config or a clock to build one, that is the design changing and it should
    fail here first.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_a_corpus_that_lost_edges_is_distinguishable_from_a_small_corpus() -> None:
    """Decision #5's rule, applied to the projection: `(structure, problems)`, never a bare
    structure.

    v1's loader raised on the first bad item and a pooled 69-schema build died with no clue
    why; the mirror failure is worse and this project has already published on top of it — a
    *silent* skip turns "a corpus that lost half its edges" into "a corpus that merely looks
    small". Both are L-R1: absence rendered as a value.

    Assert that a corpus with one unresolvable endpoint returns problems, and that a corpus
    with no joins at all returns **none** — the second half is what stops "always report a
    problem" from passing.
    """
    pytest.fail("not implemented: see docstring")


# ── join completion, and its position in the pipeline ─────────────────────────


@UNWRITTEN
def test_a_join_reaching_context_requires_both_endpoints_not_either() -> None:
    """ADR 0005 §2.8's load-bearing row, and the reason §2.8.1 had to move it.

    `resolve(ids, references)` is a fixpoint over `Mapping[id, set[id]]`, so every edge in it
    is **disjunctive**: one id present pulls in all of its references. The rule is
    **conjunctive** — *both* endpoints pull in the join. Encoded as `table → joins touching
    it`, one endpoint pulls the join, and the join then pulls its other endpoint: FK
    neighbourhood expansion by one hop from every hit table. §2.9 sets `expand_hops = 0` and
    records that v1's default of 1 was wrong, so the natural encoding silently switches on
    the thing §2.9 switched off.

    Assert the conjunction directly: a set holding **one** endpoint of a join does not gain
    the join, and does not gain the other endpoint. Then assert a set holding both gains it.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_a_steiner_points_join_keys_reach_the_licensed_set() -> None:
    """Why completion runs after `connect` and not inside `resolve`.

    A Steiner point exists to sit on a join path, so the table pairs that most need their
    `on` clause in the prompt are exactly the ones `connect` creates — after `resolve` has
    finished. Completing joins before `connect` reproduces draft 2's failure one stage later:
    a multi-hop question reaching the model with none of the keys for the hops `connect`
    chose.

    **Fixture shape.** Three tables, edges `a—b` and `b—c`, terminals `{a, c}`. `b` is the
    Steiner point. Assert both joins are present at the end, and that they are marked
    `pulled_in` and exempt from the join budget (§2.8). Assert against the **final** set, not
    `resolve`'s output — an assertion on `resolve` passes for the wrong reason here, since at
    that point `b` is not in the set at all and neither join is expected.
    """
    pytest.fail("not implemented: see docstring")
