"""The corpus structure projection: ADR 0005 §2.8.2's acceptance criterion.

**Written 2026-08-03, before the module exists** — the opposite ordering from parcel F's
contract, and the reason this one can prevent rather than convict.

It exists because of what F's contract found by execution. `serve/state.py` declares five
inputs that `resolve` and `connect` read — `join_edges`, `references`, `asset_types`,
`table_schemas`, `schema_tags` — under the comment "F1 test / wiring hooks (optional)", and
**not one of them is written anywhere**: not in `src/`, not in `tests/`, not by the eval
harness. So `connect` has run on an empty edge set on every turn this system has ever
served, and declines `missing_join_path` the moment a turn licenses two tables. Single-table
turns answer. That is why a green suite and a live eval both missed it.

**A note on where this sits.** The projection belongs in `retrieve/`, which is parcel E, and
E is in `ACCEPTED`. E's sign-off was given against scoring, fusion, routing and closure — it
did not cover this module, which did not exist. `tests/contracts.py` tracks acceptance per
*package*, so it cannot say "E accepted, this module not"; this file is separate and strictly
marked so the distinction survives that limitation rather than being absorbed by it.

**Do not edit this file to make it pass.** If a test looks wrong, stop and say so.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from contracts import needs  # noqa: E402

#: A specification with no body. Per test, never module-level: held at module level, one
#: deletion disarms every tripwire at once, and deleting it is what the first passing fix
#: forces. See ``tests/serve/test_turn_contract.py`` for the incident that established this.
#:
#: **Unapplied in this file today** — every specification below has a body. It is kept as the
#: vocabulary for the next one written here; nothing checks that, because
#: ``tools/check_declared_is_consumed.py`` does not scan ``tests/``.
UNWRITTEN = pytest.mark.xfail(strict=True, reason="contract specified, body not yet written")

pytestmark = [needs("E")]


# ── the fixture builders the specifications name ───────────────────────────────
#
# Three constructors rather than per-test literals: every specification below names a
# corpus of schemas, tables and joins, and the *only* fields any of them turns on are
# the ones passed here. Written for this file rather than imported from
# ``tests/serve/conftest.py``, whose two-schema corpus has no joins at all.


def _schema(name: str) -> Any:
    from governed_bi.corpus.schema import SchemaAsset

    return SchemaAsset(id=name, name=name, summary=f"{name} schema for the projection")


def _table(schema: str, physical: str, *, columns: tuple[str, ...] = ()) -> Any:
    from governed_bi.corpus.identity import table_id
    from governed_bi.corpus.schema import TableAsset

    return TableAsset(
        id=table_id(schema, physical),
        schema=schema,
        physical_name=physical,
        summary=f"{physical} table in {schema}",
        columns=columns,
    )


def _join(schema: str, left: str, right: str, on: str) -> Any:
    """A ``JoinAsset`` whose id is minted by ``join_id``, never hand-written.

    So that an edge dropped for being *ambiguous* cannot be confused with one dropped
    for being invalid — the summary carries both bare endpoint names, which is what
    ``problems_with`` checks.
    """
    from governed_bi.corpus.identity import join_id
    from governed_bi.corpus.schema import JoinAsset

    bare = (left.rsplit(".", 1)[-1], right.rsplit(".", 1)[-1])
    return JoinAsset(
        id=join_id(schema, left, right, on),
        left_table=left,
        right_table=right,
        on=on,
        summary=f"{bare[0]} joins {bare[1]} on {on}",
    )


# ── node identity: the reconciliation, and it must never guess ─────────────────


def test_an_ambiguous_endpoint_is_dropped_and_recorded() -> None:
    """The case where a guess fails **open**, which is why guessing is prohibited.

    `connect`'s nodes are asset ids (`{schema}.{slug(physical)}` — the slug, not the raw
    physical name, per `corpus/identity.py::table_id`), because they must match the
    identifiers in `licensed`. `JoinAsset` carries `left_table` / `right_table` as physical
    names, **bare or qualified** — `corpus/validate.py`'s `_bare()` accepts both and the ADR
    explicitly declines to settle which. So binding an edge is a lookup, and the lookup can
    find two answers.

    One physical name in two schemas is the *normal* shape of a pooled lake, not a corner
    case. Resolving it by first-match or left-most would license a table in the wrong schema
    and account `crossings` against the wrong pair — a licensing leak, not a lost edge.

    So: the edge is dropped, **and a problem is recorded**. Dropping alone fails closed but
    silently, and the failure then surfaces three layers away as `missing_join_path` on a
    turn that looked ordinary.

    **Fixture shape.** Two `SchemaAsset`s, each with a `TableAsset` whose `physical_name` is
    `customers` — ids `sales_a.customers` and `ops_b.customers`. One `JoinAsset` with
    `left_table="customers"` (bare, ambiguous) and a `right_table` that resolves cleanly.
    Mint the join's id with `join_id` (`corpus/identity.py::join_id`) so the asset is well-formed
    by the rules `problems_with` already enforces — an edge dropped for being *invalid* would
    prove nothing about an edge dropped for being *ambiguous*.

    Assert both halves. The edge is absent from the projection, and the returned problems
    name that join's id. Asserting only the first is satisfied by a projection that drops
    every edge.
    """
    from governed_bi.retrieve.structure import build_structure

    assets = [
        _schema("sales_a"),
        _schema("ops_b"),
        _table("sales_a", "customers"),
        _table("ops_b", "customers"),
        _table("sales_a", "orders"),
        # `customers` names a table in both schemas; `orders` names one in exactly one.
        _join("sales_a", "customers", "orders", "customers.id = orders.cid"),
    ]
    ambiguous = assets[-1]
    structure, problems = build_structure(assets)

    assert structure.join_edges == frozenset(), (
        "the only join has an ambiguous endpoint, so the projection must hold no edge: "
        f"got {sorted(structure.join_edges)}"
    )
    assert any(ambiguous.id in f"{p.where} {p.reason}" for p in problems), (
        f"the dropped edge is not recorded against {ambiguous.id!r}: {[str(p) for p in problems]}. "
        "Dropping alone fails closed but silently, and the silence resurfaces as "
        "missing_join_path on a turn that looks ordinary"
    )


def test_an_ambiguous_endpoint_does_not_bind_to_either_candidate() -> None:
    """The previous test's assertion stated in the form that catches the tempting fix.

    "Ambiguous endpoints are dropped" is satisfiable by code that drops the *second* match
    and keeps the first, if the problem is recorded anyway. That is precisely the fail-open
    behaviour, with a log line.

    So assert the absence of **both** candidate edges by name, not the count of edges: no
    edge incident to `sales_a.customers`, and none incident to `ops_b.customers`, from that
    join. A count assertion passes if one edge was dropped and a different one invented.

    *Amended after review:* the body earns more than that, and the docstring should say so
    or someone will simplify it back. It asserts the refusal on **three surfaces** —
    `join_edges`, `references`, and `joins_by_edge` — because a bound endpoint leaks into
    `licensed` by two routes, the Steiner edge and the reference closure, and only the first
    is what "an edge was dropped" naturally describes. Verified non-vacuous by mutation:
    binding an ambiguous endpoint to the lowest-sorted candidate fails this test and the one
    above, and no others.
    """
    from governed_bi.retrieve.structure import build_structure

    join = _join("sales_a", "customers", "orders", "customers.id = orders.cid")
    structure, _problems = build_structure(
        [
            _schema("sales_a"),
            _schema("ops_b"),
            _table("sales_a", "customers"),
            _table("ops_b", "customers"),
            _table("sales_a", "orders"),
            join,
        ]
    )
    candidates = {"sales_a.customers", "ops_b.customers"}

    bound = {node for edge in structure.join_edges for node in edge} & candidates
    assert bound == set(), (
        f"an ambiguous endpoint bound to {sorted(bound)}. Dropping the second match and keeping "
        "the first is the fail-open behaviour with a log line: a Steiner point in the wrong "
        "schema, licensed, with crossings charged to the wrong pair"
    )
    # The same statement about the closure, which is the other half of `licensed`: the join
    # must not pull in either candidate as an endpoint either.
    closed = set(structure.references.get(join.id, frozenset())) & candidates
    assert closed == set(), (
        f"the dropped join still closes onto {sorted(closed)} by reference, which licenses the "
        "table the edge was refused for"
    )
    assert structure.joins_by_edge == {}, (
        f"the join is indexed on an edge it was refused: {structure.joins_by_edge}. "
        "complete_joins would then license it from the two tables it never bound"
    )


def test_a_bare_and_a_qualified_endpoint_produce_the_same_edge() -> None:
    """The control, and without it every test above is satisfied by dropping everything.

    `validate.py` accepts `customers` and `sales_a.customers` as the same identifier, so a
    corpus containing both forms is valid and both must bind — to the *same* edge, with
    asset-id endpoints. Two `JoinAsset`s that differ only in the qualification of an endpoint
    are the same relationship: `join_id` already digests the ON clause for exactly this
    reason, and §1.2 records that collapsing two relationships between one table pair cost
    33 of 57 schemas an edge.

    **Fixture shape.** One schema, `customers` and `orders`, and two joins whose `on` is the
    same clause with the operands written in the other order — `on_digest` normalises that,
    so they must mint the same `join_id`, and the projection must not report a problem for
    the duplicate.
    """
    from governed_bi.retrieve.connect import canon_edge
    from governed_bi.retrieve.structure import build_structure

    bare = _join("sales_a", "customers", "orders", "customers.id = orders.cid")
    qualified = _join("sales_a", "sales_a.customers", "orders", "orders.cid = customers.id")
    assert bare.id == qualified.id, (
        "two joins that differ only in the qualification of an endpoint are the same "
        f"relationship, so join_id must digest them alike: {bare.id} vs {qualified.id}"
    )

    structure, problems = build_structure(
        [
            _schema("sales_a"),
            _table("sales_a", "customers"),
            _table("sales_a", "orders"),
            bare,
            qualified,
        ]
    )

    edge = canon_edge("sales_a.customers", "sales_a.orders")
    assert structure.join_edges == frozenset({edge}), (
        "a bare and a qualified spelling of one endpoint must produce one edge with asset-id "
        f"endpoints: got {sorted(structure.join_edges)}"
    )
    assert structure.joins_by_edge == {edge: (bare.id,)}, (
        f"the relationship is indexed as {structure.joins_by_edge}, not once on its edge"
    )
    assert problems == [], (
        "a corpus carrying both accepted spellings is valid — `validate.py`'s `_bare()` accepts "
        f"either — so nothing here is a defect to report: {[str(p) for p in problems]}"
    )


def test_the_edge_endpoints_are_asset_ids_and_not_physical_names() -> None:
    """The namespace assertion, stated on its own because nothing else in the system does.

    `retrieve/connect.py` compares edge endpoints against `terminals` by identity, and
    `terminals` comes from `licensed` / `by_type["table"]` — asset ids. An edge carrying
    `("customers", "orders")` is not wrong-looking anywhere: `_adjacency` builds happily,
    `_canon_edge` canonicalises happily, and `connect` then reports every terminal missing
    and declines. The two namespaces never meet, so nothing raises.

    Assert the endpoints are the ids, `{schema}.{slug(physical)}`. And use `table_id` to say so —
    ADR 0005 §2.8.2 requires it to become a declared function beside `derive_column_id` and
    `join_id`, because this reconciliation is the one place a second hand-written copy of the
    convention would silently mis-license a table.
    """
    from governed_bi.corpus.identity import table_id
    from governed_bi.retrieve.connect import canon_edge
    from governed_bi.retrieve.structure import build_structure

    structure, problems = build_structure(
        [
            _schema("sales_a"),
            _table("sales_a", "customers"),
            _table("sales_a", "orders"),
            _join("sales_a", "customers", "orders", "customers.id = orders.cid"),
        ]
    )
    assert problems == [], [str(p) for p in problems]

    expected = canon_edge(
        table_id("sales_a", "customers"), table_id("sales_a", "orders")
    )
    assert structure.join_edges == frozenset({expected}), (
        f"edge endpoints are {sorted(structure.join_edges)}, not the asset ids "
        f"{expected}. `connect` compares endpoints against terminals drawn from "
        "`licensed`, so physical names there make every terminal look missing and the "
        "turn declines — and nothing raises, because the two namespaces never meet"
    )
    physical = {"customers", "orders"}
    assert {node for e in structure.join_edges for node in e} & physical == set(), (
        "a bare physical name reached the edge set"
    )


# ── the projection is a function of the corpus, not of a turn ─────────────────


def test_the_projection_depends_on_nothing_but_the_asset_set() -> None:
    """Why this is built once beside the index rather than per turn.

    §2.2 already settled the same question for schema tags — *"computed at build, not query
    time"*. The argument is not that recomputing is wasteful. It is that a per-turn
    derivation is a place where **two turns can disagree about the shape of the corpus**, and
    a run whose turns disagree cannot be compared to anything, which is how v1's numbers
    died.

    Assert the projection is a pure function: the same assets in a different order produce an
    equal structure, and building twice produces equal structures. If a signature ever needs
    a question, a config or a clock to build one, that is the design changing and it should
    fail here first.
    """
    import inspect

    from governed_bi.retrieve.structure import build_structure

    assets = [
        _schema("sales_a"),
        _table("sales_a", "customers", columns=("sales_a.customers.id",)),
        _table("sales_a", "orders"),
        _table("sales_a", "invoices"),
        _join("sales_a", "customers", "orders", "customers.id = orders.cid"),
        _join("sales_a", "orders", "invoices", "orders.id = invoices.oid"),
    ]
    from governed_bi.corpus.schema import ColumnAsset

    assets.append(
        ColumnAsset(
            id="sales_a.customers.id",
            schema="sales_a",
            parent_table="customers",
            physical_name="id",
            summary="customers.id (integer)",
        )
    )

    first, first_problems = build_structure(assets)
    again, again_problems = build_structure(assets)
    shuffled, shuffled_problems = build_structure(list(reversed(assets)))

    assert first == again, "building twice over one asset set produced two structures"
    assert first == shuffled, (
        "the same assets in a different order produced a different structure, so two turns "
        "reading the corpus in two orders would disagree about its shape"
    )
    assert first_problems == again_problems == shuffled_problems == []

    params = list(inspect.signature(build_structure).parameters)
    assert params == ["assets"], (
        f"build_structure takes {params}. It is a projection of the asset set: a question, a "
        "config or a clock in this signature is the design changing"
    )


def test_a_corpus_that_lost_edges_is_distinguishable_from_a_small_corpus() -> None:
    """Decision #5's rule, applied to the projection: `(structure, problems)`, never a bare
    structure.

    v1's loader raised on the first bad item and a pooled 69-schema build died with no clue
    why; the mirror failure is worse and this project has already published on top of it — a
    *silent* skip turns "a corpus that lost half its edges" into "a corpus that merely looks
    small". Both are L-R1: absence rendered as a value.

    Assert that a corpus with one unresolvable endpoint returns problems, and that a corpus
    with no joins at all returns **none** — the second half is what stops "always report a
    problem" from passing.
    """
    from governed_bi.retrieve.structure import build_structure

    tables = [_schema("sales_a"), _table("sales_a", "customers"), _table("sales_a", "orders")]

    lost = _join("sales_a", "customers", "nowhere", "customers.id = nowhere.cid")
    lossy, lossy_problems = build_structure([*tables, lost])
    assert lossy.join_edges == frozenset(), "an endpoint naming nothing must not bind"
    assert lossy_problems, (
        "a corpus that lost its only edge is indistinguishable from a corpus with no edges. "
        "Both are L-R1: absence rendered as a value"
    )
    assert any(lost.id in f"{p.where} {p.reason}" for p in lossy_problems), (
        f"the problem does not name the join that lost the edge: {[str(p) for p in lossy_problems]}"
    )

    small, small_problems = build_structure(tables)
    assert small.join_edges == frozenset()
    assert small_problems == [], (
        "a corpus with no joins is small, not broken. Reporting a problem for it would make "
        f"the list unreadable and the distinction useless: {[str(p) for p in small_problems]}"
    )


# ── join completion, and its position in the pipeline ─────────────────────────


def test_a_join_reaching_context_requires_both_endpoints_not_either() -> None:
    """ADR 0005 §2.8's load-bearing row, and the reason §2.8.1 had to move it.

    `resolve(ids, references)` is a fixpoint over `Mapping[id, set[id]]`, so every edge in it
    is **disjunctive**: one id present pulls in all of its references. The rule is
    **conjunctive** — *both* endpoints pull in the join. Encoded as `table → joins touching
    it`, one endpoint pulls the join, and the join then pulls its other endpoint: FK
    neighbourhood expansion by one hop from every hit table. §2.9 sets `expand_hops = 0` and
    records that v1's default of 1 was wrong, so the natural encoding silently switches on
    the thing §2.9 switched off.

    Assert the conjunction directly: a set holding **one** endpoint of a join does not gain
    the join, and does not gain the other endpoint. Then assert a set holding both gains it.
    """
    from governed_bi.retrieve.resolve import resolve
    from governed_bi.retrieve.structure import build_structure, complete_joins

    join = _join("sales_a", "customers", "orders", "customers.id = orders.cid")
    structure, problems = build_structure(
        [
            _schema("sales_a"),
            _table("sales_a", "customers"),
            _table("sales_a", "orders"),
            join,
        ]
    )
    assert problems == [], [str(p) for p in problems]
    left, right = "sales_a.customers", "sales_a.orders"

    # One endpoint. Neither the join nor the far side may arrive — by the closure, which is
    # where the disjunctive encoding would have leaked, or by completion.
    closure = resolve({left}, references=structure.references)
    assert join.id not in closure, (
        "one endpoint pulled in the join through the reference closure. Every edge in a "
        "fixpoint over Mapping[id, set[id]] is disjunctive, so `table -> joins touching it` "
        "expands the FK neighbourhood by one hop from every hit table — which is what §2.9 "
        "turned off (expand_hops = 0, v1's 1 recorded as wrong)"
    )
    assert right not in closure, f"one endpoint reached the other: {sorted(closure)}"
    assert complete_joins({left}, structure) == frozenset(), (
        "the rule is conjunctive: one endpoint present is not both endpoints present"
    )

    # Both endpoints.
    assert complete_joins({left, right}, structure) == frozenset({join.id}), (
        "a set holding both endpoints must gain the join. Without this row a four-table "
        "question reaches the model with none of its join keys"
    )
    assert complete_joins({left, right}, structure) == complete_joins(
        {left, right} | complete_joins({left, right}, structure), structure
    ), "completion is idempotent — it is a total function of a set"


def test_a_steiner_points_join_keys_reach_the_licensed_set() -> None:
    """Why completion runs after `connect` and not inside `resolve`.

    A Steiner point exists to sit on a join path, so the table pairs that most need their
    `on` clause in the prompt are exactly the ones `connect` creates — after `resolve` has
    finished. Completing joins before `connect` reproduces draft 2's failure one stage later:
    a multi-hop question reaching the model with none of the keys for the hops `connect`
    chose.

    **Fixture shape.** Three tables, edges `a—b` and `b—c`, terminals `{a, c}`. `b` is the
    Steiner point. Assert both joins are present at the end, and that they are marked
    `pulled_in` and exempt from the join budget (§2.8). Assert against the **final** set, not
    `resolve`'s output — an assertion on `resolve` passes for the wrong reason here, since at
    that point `b` is not in the set at all and neither join is expected.
    """
    from governed_bi.register.assets import AssetType
    from governed_bi.retrieve.budget import apply_budgets, budget_for
    from governed_bi.retrieve.connect import connect
    from governed_bi.retrieve.structure import build_structure, complete_joins
    from governed_bi.serve.nodes.route_retrieve import connect_node

    a, b, c = "sales_a.a", "sales_a.b", "sales_a.c"
    ab = _join("sales_a", "a", "b", "a.id = b.aid")
    bc = _join("sales_a", "b", "c", "b.id = c.bid")
    structure, problems = build_structure(
        [
            _schema("sales_a"),
            _table("sales_a", "a"),
            _table("sales_a", "b"),
            _table("sales_a", "c"),
            ab,
            bc,
        ]
    )
    assert problems == [], [str(p) for p in problems]

    terminals = {a, c}
    result = connect(terminals, edges=structure.join_edges, max_points=5)
    assert not result.declined, "a—b—c with terminals {a, c} is connected through one point"
    assert result.added == frozenset({b}), f"b is the Steiner point; got {sorted(result.added)}"

    licensed = terminals | set(result.added)
    completed = complete_joins(licensed, structure)
    assert completed == frozenset({ab.id, bc.id}), (
        "both hops' keys must reach the final set. A Steiner point exists to sit on a join "
        "path, so completing joins before `connect` misses exactly the keys the rule is for — "
        f"got {sorted(completed)}"
    )

    # Marked `pulled_in`, against the node that assembles the final set rather than against a
    # reconstruction of it: `configurable["structure"]` is the declared wiring (§2.8.2), and
    # `connect_node` now declares `config` so `wrap.py` forwards it.
    out = connect_node(
        {"licensed": sorted(licensed), "schemas": ["sales_a"]},
        {"configurable": {"structure": structure}},
    )
    pulled_in = out["retrieved"]["pulled_in"]
    assert {ab.id, bc.id} <= set(pulled_in), (
        f"the completed joins are not in pulled_in: {pulled_in}"
    )
    assert pulled_in[ab.id] == "connect" and pulled_in[bc.id] == "connect"
    assert ab.id not in out["licensed"] and bc.id not in out["licensed"], (
        "`licensed` is govern's table allowlist (bounds.py); a join id there is a table key "
        "naming no table"
    )

    # Exempt from the join budget: `apply_budgets` caps ranked hits per type and returns
    # `pulled_in` unchanged. Asserted with the cap exhausted, so the exemption is not vacuous.
    cap = budget_for(AssetType.join)
    assert isinstance(cap, int), "the join budget is a count, so it can be exhausted"
    ranked = [(f"join_rank_{i}", AssetType.join, 1.0) for i in range(cap + 2)]
    budgeted = apply_budgets(ranked, pulled_in=[(j, AssetType.join) for j in sorted(completed)])
    assert len(budgeted.hits) == cap, "ranked joins are capped"
    assert {j for j, _ in budgeted.pulled_in} == completed, (
        "a completed join was budgeted out. These are structural additions, not ranked hits"
    )


# ── the schema tag a metric-bound term gets, which is the pooled lake's leak ────


def test_a_term_bound_to_a_metric_inherits_the_metrics_schema() -> None:
    """ADR 0008 Phase 0. **This is the pooled data lake's licensing leak.**

    ``TagRule.binding_target`` reads the target's own ``schema`` field, and three of the
    eight types have none: a metric's namespace is its ``base_table``'s. So a term bound
    to a metric came out **untagged** — and untagged is not inert. Pass two carries an
    untagged asset forward *unconditionally*, because it cannot restrict what it cannot
    place, so one lexical hit bridged schemas: a Shakespeare term pulled its metric,
    which pulled ``shakespeare.parrafos`` and four of its columns into ``licensed`` on a
    ``beer_factory`` question, and ``connect`` cannot join Shakespeare to a brewery. It
    declined ``missing_join_path`` even at ``route_top_n = 1``.

    Measured at 136 untagged terms on the gold-semantic-layer corpus before the fix, 0
    after — the 27 that remain untagged carry no ``binding`` at all, which ADR 0005 makes
    a legitimate state rather than a defect.
    """
    from governed_bi.corpus.schema import Binding, MetricAsset, TermAsset
    from governed_bi.register.assets import AssetType
    from governed_bi.retrieve.structure import build_structure

    metric = MetricAsset(
        id="metric_line_yield",
        name="line yield",
        base_table="beer_factory.batches",
        expression="AVG(litres)",
        summary="line yield: AVG(litres) per batch",
    )
    # A term bound to the *metric*, not to a column. This is the 109-asset shape in the
    # corpus, and the whole point is that `binding.target_id` is a perfectly valid asset
    # id -- the reference resolves, and only the *tag* was missing.
    term = TermAsset(
        id="term_yield",
        name="yield",
        summary="yield, output, litres per batch",
        binding=Binding(target_type=AssetType.metric, target_id=metric.id),
    )
    chained = TermAsset(
        id="term_output",
        name="output",
        summary="output — a synonym for yield",
        binding=Binding(target_type=AssetType.term, target_id=term.id),
    )
    assets = [
        _schema("beer_factory"),
        _table("beer_factory", "batches"),
        metric,
        term,
        chained,
    ]

    structure, problems = build_structure(assets)

    assert not problems, problems
    assert structure.schema_tags.get(metric.id) == "beer_factory", (
        "the metric itself is tagged through its base_table; if this fails the term "
        "cannot inherit anything and the rest of the assertion is vacuous"
    )
    assert structure.schema_tags.get(term.id) == "beer_factory", (
        f"a term bound to a metric is untagged: {structure.schema_tags.get(term.id)!r}. "
        "Pass two carries untagged assets forward unconditionally, so this term votes "
        "for no schema and is licensed against every one of them"
    )
    assert structure.schema_tags.get(chained.id) == "beer_factory", (
        "term -> term -> metric is a legitimate chain and it must resolve too, or the "
        "fix is one hop deep and the leak survives behind a synonym"
    )


def test_a_binding_cycle_does_not_hang_the_projection() -> None:
    """The tag chain is a fixpoint over a graph the corpus authors, so it may contain a
    cycle. Two terms bound to each other must simply stay untagged — the loop makes no
    progress and stops — rather than recursing until the stack ends the turn."""
    from governed_bi.corpus.schema import Binding, TermAsset
    from governed_bi.register.assets import AssetType
    from governed_bi.retrieve.structure import build_structure

    left = TermAsset(
        id="term_a",
        name="a",
        summary="a, the first term",
        binding=Binding(target_type=AssetType.term, target_id="term_b"),
    )
    right = TermAsset(
        id="term_b",
        name="b",
        summary="b, the second term",
        binding=Binding(target_type=AssetType.term, target_id="term_a"),
    )

    structure, _ = build_structure([left, right])

    assert left.id not in structure.schema_tags and right.id not in structure.schema_tags, (
        "a cycle resolved to a tag, which means something outside the corpus decided it"
    )
