"""Parcel E's acceptance criterion: scoring, fusion, routing, closure and budgets.

**Do not edit this file to make it pass.** It is the contract, authored by the design
holder before implementation, because an agent writes tests that pass against the code
it just produced. If a test looks wrong, stop and say so in your report.

Specification: ``docs/plans/v2-layer-handoffs.md`` section 6 and ADR 0005 §2.

**Why almost nothing here takes an ``Asset``.** Parcel D owns the asset types and is
being built in parallel, so assertions against its API would be assertions against an
API invented here. The scoring functions therefore take ``(id, text)`` pairs. That is
not a workaround: a scorer has no business knowing what an asset is, and the seam is
better for it. Only :func:`test_budgets_come_from_the_register` reaches into
``register/assets.py``, which is already declared and committed.

The four properties that carry this parcel, each with a specific v1 failure behind it:

1. **``cosine`` raises on a width mismatch.** v1 returned ``0.0``, so a cross-model
   cache hit degraded routing to "nothing scores" with no error anywhere. This is why
   ``Embedder`` is a port at all — ``model`` and ``dimensions`` are part of the
   interface rather than a convention each caller remembers.
2. **A channel that did not run is not a channel that scored zero.** ``lexical`` on the
   ``example`` facet is *correct* absence, by design; on ``entity`` the same absence
   means the index died. ``register/facets.py`` decides which, and ``retrieve/`` must
   never decide it locally.
3. **``fuse`` renormalises by active channels.** Otherwise a one-channel facet scores
   systematically below a two-channel one and the budget silently prefers the richer
   facet — an artefact of the arithmetic presented as relevance.
4. **``resolve`` is total, ``connect`` is not.** Conflating them reports a bounded
   best-effort path as a closure.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from contracts import needs  # noqa: E402

pytestmark = needs("E")

#: A tiny corpus as ``(id, summary)``. Deliberately built so "customer" is common and
#: "voltage" is rare, which is what makes the IDF tests below discriminating.
DOCS: list[tuple[str, str]] = [
    ("s1.customers", "customers one row per registered customer"),
    ("s1.orders", "orders one row per customer order"),
    ("s1.invoices", "invoices billing document for a customer order"),
    ("s2.sensors", "sensors voltage reading per device"),
]


# ── the vector channel ───────────────────────────────────────────────────────


def test_cosine_raises_on_a_width_mismatch() -> None:
    """The v1 incident, and the reason ``Embedder`` is a port.

    Returning ``0.0`` here made a cross-model cache hit indistinguishable from "this
    document is irrelevant", across an entire run, with nothing in any artifact.
    """
    from governed_bi.retrieve.semantic import cosine  # type: ignore[import-not-found]

    with pytest.raises(Exception):
        cosine([1.0, 0.0, 0.0], [1.0, 0.0])


def test_cosine_of_identical_vectors_is_one() -> None:
    """The control. A ``cosine`` that raises on everything also passes the test above."""
    from governed_bi.retrieve.semantic import cosine  # type: ignore[import-not-found]

    assert cosine([0.6, 0.8], [0.6, 0.8]) == pytest.approx(1.0)


def test_the_vector_cache_key_includes_model_and_dimensions() -> None:
    """v1's cache key omitted both, which is what allowed the mismatch above to be a
    *cache hit* rather than a miss. Two embedders differing only in model must not
    share an entry."""
    from governed_bi.retrieve.semantic import cache_key  # type: ignore[import-not-found]

    a = cache_key("customers", model="text-embedding-3-large", dimensions=3072)
    b = cache_key("customers", model="text-embedding-3-small", dimensions=3072)
    c = cache_key("customers", model="text-embedding-3-large", dimensions=1536)
    assert len({a, b, c}) == 3


# ── the lexical channel ──────────────────────────────────────────────────────


def test_bm25_scores_are_absolute_not_relative_to_the_best_hit() -> None:
    """Saturating normalisation ``s/(s+k)``, per ADR 0005 §2.

    A score divided by the current query's best hit is only comparable *within* one
    query, so it cannot be summed across facets in ``route`` or weighted against a
    cosine in ``fuse``. The check: a query whose best match is weak must not have its
    top hit normalised up to the same value as a query whose best match is strong.
    """
    from governed_bi.retrieve.lexical import BM25  # type: ignore[import-not-found]

    index = BM25(DOCS)
    strong = max(s for _, s in index.search("customers registered"))
    weak = max(s for _, s in index.search("customer"))
    assert strong != pytest.approx(weak), (
        "both queries' top hits normalised to the same value, so the score is relative "
        "to the query rather than absolute"
    )
    for _, score in index.search("customers registered"):
        assert 0.0 <= score <= 1.0


def test_idf_is_global_not_computed_within_the_selected_schemas() -> None:
    """Settled in ADR 0005: global IDF. Within-schema is an open question, not an option.

    A term's rarity must not change because routing narrowed the candidate set —
    otherwise the second pass rescores documents on a different scale than the first,
    and the two passes' scores stop being comparable even though both are called
    "lexical".
    """
    from governed_bi.retrieve.lexical import BM25  # type: ignore[import-not-found]

    full = BM25(DOCS)
    narrowed = full.restrict_to({"s1.customers", "s1.orders"})
    a = dict(full.search("customer"))["s1.orders"]
    b = dict(narrowed.search("customer"))["s1.orders"]
    assert a == pytest.approx(b), (
        "restricting the candidate set changed a document's score, so IDF was "
        "recomputed within the subset"
    )


# ── fusion ───────────────────────────────────────────────────────────────────


def test_fuse_renormalises_by_the_active_channels() -> None:
    """Property 3. A one-channel facet must not be systematically penalised.

    A document scoring 0.8 on its only active channel must fuse to 0.8, not to
    ``0.5 * 0.8`` — otherwise ``example`` (semantic only, by design) always ranks below
    ``entity`` (both channels) for equal relevance, and the per-type budget then
    allocates on an artefact of the arithmetic.
    """
    from governed_bi.retrieve.fuse import fuse  # type: ignore[import-not-found]

    both = fuse({"lexical": 0.8, "semantic": 0.8}, weights={"lexical": 0.5, "semantic": 0.5})
    one = fuse({"semantic": 0.8}, weights={"lexical": 0.5, "semantic": 0.5})
    assert both == pytest.approx(0.8)
    assert one == pytest.approx(0.8)


def test_fuse_distinguishes_a_channel_that_did_not_run_from_one_that_scored_zero() -> None:
    """Property 2, and L-R1. These two inputs must not fuse to the same number.

    A document that a channel *scored at zero* is evidence of irrelevance. A document
    that channel never saw is no evidence at all, and treating it as zero is the
    25-times-recurring v1 defect.
    """
    from governed_bi.retrieve.fuse import fuse  # type: ignore[import-not-found]

    weights = {"lexical": 0.5, "semantic": 0.5}
    scored_zero = fuse({"lexical": 0.0, "semantic": 0.8}, weights=weights)
    did_not_run = fuse({"semantic": 0.8}, weights=weights)
    assert scored_zero != pytest.approx(did_not_run)


def test_fuse_refuses_an_unknown_channel() -> None:
    """A typo'd channel name must not be silently dropped from the denominator, which
    would look like a legitimate one-channel fusion."""
    from governed_bi.retrieve.fuse import fuse  # type: ignore[import-not-found]

    with pytest.raises(Exception):
        fuse({"lexicel": 0.8}, weights={"lexical": 0.5, "semantic": 0.5})


# ── routing ──────────────────────────────────────────────────────────────────


def test_route_takes_the_per_facet_max_then_sums_across_facets() -> None:
    """ADR 0005 §2.5's arithmetic, asserted against hand-computed values.

    Per-facet **max** so a schema with forty weak hits in one facet does not outrank a
    schema with one strong hit; **summed** across facets so agreement between facets is
    what accumulates. Written as literals rather than re-derived, because a test that
    recomputes the rule it checks passes when the rule is inverted — which is exactly
    how v1's gold gate survived a reversed denominator.
    """
    from governed_bi.retrieve.route import route  # type: ignore[import-not-found]

    hits = [
        ("facet_entity", "s1", 0.9),
        ("facet_entity", "s1", 0.4),
        ("facet_term", "s1", 0.5),
        ("facet_entity", "s2", 0.6),
        ("facet_term", "s2", 0.6),
        ("facet_metric", "s2", 0.6),
    ]
    scores = dict(route(hits))
    assert scores["s1"] == pytest.approx(1.4)  # max(0.9, 0.4) + 0.5
    assert scores["s2"] == pytest.approx(1.8)  # 0.6 + 0.6 + 0.6
    assert max(scores, key=lambda k: scores[k]) == "s2", "facet agreement must accumulate"


def test_route_runs_before_budgets_are_applied() -> None:
    """ADR 0005 §2.5: ordering ``route`` before budgets is load-bearing.

    Had budgets applied first, ``route`` would aggregate a budget-truncated residue and
    a schema's rank would depend on how many of its assets survived a per-type cap.
    """
    from governed_bi.retrieve import route as module  # type: ignore[import-not-found]

    source = Path(module.__file__).read_text(encoding="utf-8")
    assert "budget" not in source.replace("budgets are applied", ""), (
        "route imports or applies budgets; it must aggregate the untruncated hit set"
    )


# ── closure vs best-effort ───────────────────────────────────────────────────


def test_resolve_is_total_and_idempotent() -> None:
    """Property 4. ``resolve`` is reference closure: a total function of the hit set.

    Applying it twice must change nothing. If it does, it is not a closure, and
    whatever it *is* depends on call order — which is unreportable.
    """
    from governed_bi.retrieve.resolve import resolve  # type: ignore[import-not-found]

    refs = {"s1.orders": {"s1.customers"}, "s1.customers": set(), "s1.invoices": {"s1.orders"}}
    once = resolve({"s1.invoices"}, references=refs)
    assert once == resolve(once, references=refs)
    assert {"s1.invoices", "s1.orders", "s1.customers"} <= once


def test_connect_is_bounded_and_reports_the_path_it_chose() -> None:
    """``connect`` is Steiner and **can pick a wrong path**, so it must say which.

    A join path reported without its identity cannot be audited when the answer is
    wrong, and "the model joined badly" and "we handed it a bad path" are different
    diagnoses that this field is the only way to separate.
    """
    from governed_bi.retrieve.connect import connect  # type: ignore[import-not-found]

    edges = {("s1.orders", "s1.customers"), ("s1.invoices", "s1.orders")}
    result = connect({"s1.invoices", "s1.customers"}, edges=edges, max_points=5)
    assert result.path, "connect must report the path it chose"
    assert "s1.orders" in result.added


def test_connect_declines_rather_than_truncating_past_its_bound() -> None:
    """ADR 0005: exceeding ``max_steiner_points`` is **a refusal, not a silent
    expansion**. A truncated path is a wrong path presented as a found one."""
    from governed_bi.retrieve.connect import connect  # type: ignore[import-not-found]

    chain = {(f"t{i}", f"t{i+1}") for i in range(12)}
    result = connect({"t0", "t12"}, edges=chain, max_points=2)
    assert result.declined is True
    assert not result.added


# ── budgets and attribution ──────────────────────────────────────────────────


def test_budgets_come_from_the_register() -> None:
    """``budgets.get(cls, 0)`` is the shape to keep unrepresentable.

    v1 kept the budget in one table and the type in another; they disagreed, and
    ``NegativeExampleAsset`` was embedded, indexed and structurally unretrievable. The
    budget is a column of the asset policy row in ``register/assets.py``.
    """
    from governed_bi.register import assets
    from governed_bi.retrieve import budget as module  # type: ignore[import-not-found]

    for asset_type in assets.AssetType:
        assert module.budget_for(asset_type) is not None, (
            f"{asset_type.value} has no budget; a dict default of 0 makes a type "
            "unretrievable while leaving it in the index"
        )


def test_pulled_in_assets_do_not_consume_budget_and_stay_distinguishable() -> None:
    """ADR 0005 §2.5. ``resolve``/``connect`` additions are not ranked hits.

    Both halves matter: charging them to the budget would evict *hits* in favour of
    structural neighbours, and merging them into the hit list would make attribution
    claim retrieval found something it did not.
    """
    from governed_bi.register import assets
    from governed_bi.retrieve.budget import apply_budgets  # type: ignore[import-not-found]

    cap = assets.ASSET_REGISTER[assets.AssetType.table].budget
    assert isinstance(cap, int), "this test assumes table has a numeric budget"
    hits = [(f"hit{i}", assets.AssetType.table, 1.0 - i / 100) for i in range(cap + 3)]
    pulled = [(f"pull{i}", assets.AssetType.table) for i in range(5)]

    result = apply_budgets(hits, pulled_in=pulled)
    assert len(result.hits) == cap
    assert len(result.pulled_in) == 5, "pulled-in assets must survive the budget"
    assert not (set(result.hits) & set(result.pulled_in))


def test_a_hit_carries_its_facet_both_channel_scores_and_every_query_that_hit() -> None:
    """Attribution built in, per ADR 0005 §2.

    v1 could not answer "which facet found this and on which channel", so every
    retrieval post-mortem was a reconstruction. ``queries`` is plural because a facet
    issues several and knowing which one matched is what makes extraction debuggable.
    """
    from governed_bi.retrieve.result import Hit  # type: ignore[import-not-found]

    fields = set(Hit.__dataclass_fields__)  # type: ignore[attr-defined]
    assert {"facet", "asset_id", "asset_type", "lexical", "semantic", "queries"} <= fields
