"""Parcel I's acceptance criterion: the `Embedder` port's adapters.

**Written 2026-08-03, before the adapters exist.** `ports.py:96` already names the three
this file governs — `model/openai_embedder.py`, `model/bedrock_embedder.py`,
`model/deterministic_embedder.py` — and states that the deterministic one *"is a third
adapter, not a courtesy fake"*, because it is what makes ADR 0005's implementation steps
6–9 model-free.

**Do not edit this file to make it pass.** If a test looks wrong, stop and say so.

Every specification below is parametrised over **every** adapter, deliberately. One adapter
is a hypothetical seam; the port earns its existence only if two independent
implementations satisfy one contract, and v1's fake discarded the arguments it was handed,
so a contract only the real adapter met would have caught nothing.

The through-line is narrower than usual and it is worth stating, because the port's own
docstring gives the reason it exists: **the model identity and the width are part of the
interface, not metadata beside it.** v1's vector cache omitted both, and `cosine` returned
`0.0` on a width mismatch rather than raising, so a cross-model cache hit degraded routing
to "nothing scores" with no error anywhere. `retrieve/semantic.py:18` now raises on a width
mismatch — which closes the case the widths *differ* and leaves open the one they agree,
which is the case this contract is mostly about.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from contracts import needs  # noqa: E402

#: A specification with no body. Per test, never module-level — see
#: ``tests/serve/test_turn_contract.py`` for the incident that established that.
UNWRITTEN = pytest.mark.xfail(strict=True, reason="contract specified, body not yet written")

pytestmark = [needs("I")]

#: Every adapter, by import path. The OpenAI one must **skip loudly** without a key, naming
#: the environment variable and never printing its value; a silent skip is a green suite
#: that tested one adapter and reported two.
ADAPTERS = ("deterministic", "openai")


# ── the interface, on every adapter ───────────────────────────────────────────


@pytest.mark.parametrize("adapter", ADAPTERS)
def test_embed_returns_one_vector_per_input_in_input_order(adapter: str) -> None:
    """`ports.py:113` — *"A shorter or reordered result is a bug in the adapter, never
    something the caller reconciles."*

    `retrieve/index.py:131` zips the returned vectors against the texts it asked for with
    `strict=True`, so a **short** result raises. A **reordered** one does not: every asset
    silently gets another asset's vector, every score is wrong, and nothing anywhere
    disagrees. That is the failure this test exists for, and it is invisible to any
    single-input test.

    **Fixture shape.** Embed a list long enough to **cross the adapter's batch boundary** —
    batching is the only place order breaks, so a batch-sized input is the whole point.
    Make each text distinguishable, embed them a second time individually, and assert the
    batched vector for text *i* equals the individual vector for text *i*.

    Equality on floats: OpenAI is not bit-identical across calls, so compare with a
    tolerance, and assert the **nearest neighbour of each individual vector is its own
    batched vector** rather than an exact match. A tolerance loose enough to pass a
    reordering is worse than no test.
    """
    from embedders import NARROW_DIMENSIONS, SMALL_BATCH, make_embedder
    from governed_bi.retrieve.semantic import cosine

    embedder = make_embedder(adapter, dimensions=NARROW_DIMENSIONS, batch_size=SMALL_BATCH)

    # Seven inputs over a batch size of four, so the batches are [0:4] and [4:7] and the
    # boundary is crossed. Seven unrelated topics, because the assertion below is an
    # argmax and two near-synonyms would make it a coin toss rather than a check.
    texts = [
        "customers registered in the sales schema",
        "brewing capacity per factory site",
        "geographic coordinates of each location",
        "invoice totals by billing month",
        "employee shift rota for the packaging line",
        "supplier contracts and their renewal dates",
        "returned bottles counted at the depot",
    ]
    assert len(texts) > embedder.batch_size, "fixture no longer crosses a batch boundary"

    batched = embedder.embed(texts)
    assert len(batched) == len(texts)

    individual = [embedder.embed([text])[0] for text in texts]

    for position, own in enumerate(individual):
        similarities = [cosine(own, candidate) for candidate in batched]
        nearest = max(range(len(similarities)), key=similarities.__getitem__)
        assert nearest == position, (
            f"input {position} ({texts[position]!r}) embedded alone is nearest to "
            f"batched vector {nearest} ({texts[nearest]!r}): the batch came back "
            "reordered, so every asset would silently take another asset's vector"
        )
        # A **margin** over the runner-up, not proximity to 1.0. Amended 2026-08-03 after
        # `approx(1.0, abs=1e-3)` flaked once against OpenAI: the provider is not bit-identical
        # across calls, and a contract test that needs a re-run teaches people to re-run. The
        # margin is also the stronger claim — "this vector is the same text's" is what the
        # ordering guarantee says, and it stays true at any absolute similarity.
        runner_up = max(s for i, s in enumerate(similarities) if i != position)
        assert similarities[position] - runner_up > 0.05, (
            f"input {position} is nearest to its own batched vector by only "
            f"{similarities[position] - runner_up:.4f}: too close to call, so this body "
            "cannot distinguish a correct batch from a reordered one"
        )


@pytest.mark.parametrize("adapter", ADAPTERS)
def test_every_vector_has_exactly_the_declared_width(adapter: str) -> None:
    """`dimensions` is a property of the port, and `text-embedding-3-large` can be asked
    for a **shortened** width — so "the width the API returned" and "the width the adapter
    declares" are two facts, and only one of them is in the interface.

    Assert they agree: `len(v) == adapter.dimensions` for every returned vector. If the
    adapter accepts a `dimensions` argument, assert it for a shortened width too, because a
    request the API ignored would otherwise pass unnoticed.
    """
    from embedders import NARROW_DIMENSIONS, make_embedder

    probe = ["a customers table", "a brewing capacity metric"]

    native = make_embedder(adapter)
    vectors = native.embed(probe)
    assert [len(v) for v in vectors] == [native.dimensions, native.dimensions]

    # The shortened width, which is the half that can pass unnoticed: the adapter
    # declares 64 and the provider is free to hand back its native width instead.
    shortened = make_embedder(adapter, dimensions=NARROW_DIMENSIONS)
    assert shortened.dimensions == NARROW_DIMENSIONS
    assert shortened.dimensions != native.dimensions, (
        "the shortened width equals the native one, so this body would pass for an "
        "adapter that ignored `dimensions` entirely"
    )
    short_vectors = shortened.embed(probe)
    assert [len(v) for v in short_vectors] == [NARROW_DIMENSIONS, NARROW_DIMENSIONS]


@pytest.mark.parametrize("adapter", ADAPTERS)
def test_an_empty_or_whitespace_input_refuses(adapter: str) -> None:
    """`ports.py:118` states the hazard and the reason it cannot be papered over: *OpenAI
    accepts it and returns a vector that can score above zero and pollute a ranking*, while
    Bedrock rejects it. So the adapters would disagree, and the disagreement would surface
    as a ranking that is subtly wrong on one provider only.

    The port says callers must not pass one. **The adapter must refuse anyway** — a rule
    only the caller enforces is a rule that holds until a new caller exists. Assert both
    `""` and `"   "` raise, on every adapter, and assert **nothing is returned** rather than
    a zero vector: a zero vector is "not measured" rendered as "scores nothing", and
    `cosine` cannot distinguish it from a real vector that happens to be orthogonal.
    """
    from embedders import NARROW_DIMENSIONS, make_embedder

    embedder = make_embedder(adapter, dimensions=NARROW_DIMENSIONS)

    for blank in ("", "   ", "\t\n "):
        with pytest.raises(ValueError):
            embedder.embed([blank])
        # Alongside a real summary: a batch is where a blank rides in unnoticed, and an
        # adapter that validated only single-element input would pass the line above.
        with pytest.raises(ValueError):
            embedder.embed(["a customers table", blank])
        with pytest.raises(ValueError):
            embedder.embed([blank, "a customers table"])

    # Nothing came back in place of a vector -- no zero vector, no shortened list. The
    # control is the same call with real text, which an adapter that raises on
    # everything would fail.
    good = embedder.embed(["a customers table"])
    assert len(good) == 1
    assert len(good[0]) == NARROW_DIMENSIONS
    assert any(component != 0.0 for component in good[0])


# ── the cache key, which is where v1 actually died ────────────────────────────


def test_two_models_of_the_same_width_do_not_share_a_cache_entry() -> None:
    """**The most important test in this file, and the one the existing fix does not
    cover.**

    `retrieve/index.py:103` takes `vector_cache: Mapping[str, Vector]` keyed on the
    **summary text alone**. `register/knobs.py:208` says `embedding_model` is *"part of
    every vector cache key"*. Those two statements contradict each other, and `cosine`
    raising on a width mismatch (`semantic.py:18`) closes only the case where the widths
    **differ**.

    `text-embedding-3-large` accepts a `dimensions` argument. So a 1536-wide
    `text-embedding-3-large` and a 1536-wide `text-embedding-3-small` are **width-identical
    and semantically unrelated**, and the one backstop in the system cannot tell them apart.
    That is v1's defect surviving in the exact shape the fix does not reach.

    Assert that a cache populated by one model is not reused by another of the same width.
    Wherever the key is formed, `(model, dimensions, text)` must be in it — not text alone.

    **This is a specification about a signature, not only a behaviour.** If satisfying it
    means changing `build_index`'s `vector_cache` parameter, change it; a cache that is
    correct only when the caller remembers to keep one dict per model is the convention this
    port exists to replace.
    """
    from typing import Any, Sequence

    from governed_bi.model import DeterministicEmbedder
    from governed_bi.ports import Vector
    from governed_bi.register.assets import AssetType
    from governed_bi.retrieve.index import IndexEntry, build_index
    from governed_bi.retrieve.semantic import cache_key, cosine

    class Counting(DeterministicEmbedder):
        """Records the texts it was actually asked to embed.

        A cache hit and a cache miss produce the same ``UnifiedIndex``, so "was this
        reused" cannot be read off the result. Without this, a cache that **never** hits
        satisfies every non-reuse assertion below.
        """

        def __init__(self, **kwargs: Any) -> None:
            super().__init__(**kwargs)
            self.embedded: list[str] = []

        def _embed_batch(self, texts: Sequence[str]) -> list[Vector]:
            self.embedded.extend(texts)
            return super()._embed_batch(texts)

    width = 64
    summary = "customers registered in the sales schema"

    def entries() -> list[IndexEntry]:
        return [
            IndexEntry(
                id="t1",
                summary=summary,
                asset_type=AssetType.table,
                schema_tag="sales",
            )
        ]

    # The pair the one existing backstop cannot separate: same width, different model.
    # `semantic.py:18` raises when widths differ and these agree, so nothing downstream
    # can tell a cross-model hit from a legitimate one.
    large = Counting(dimensions=width, salt="stands-in-for-3-large")
    small = Counting(dimensions=width, salt="stands-in-for-3-small")
    assert large.dimensions == small.dimensions == width
    assert large.model != small.model

    cache: dict[str, Vector] = {}

    first = build_index(entries(), embedder=large, vector_cache=cache)
    assert large.embedded == [summary]
    assert cache_key(summary, model=large.model, dimensions=width) in cache

    # Same text, same width, different model -> a MISS.
    second = build_index(entries(), embedder=small, vector_cache=cache)
    assert small.embedded == [summary], (
        "the second model was handed the first model's vector: the cache key is not "
        "carrying the model, which is v1's defect exactly"
    )
    assert len(cache) == 2
    assert cache_key(summary, model=small.model, dimensions=width) in cache

    # ...and the two vectors really are unrelated, so a shared entry would have been
    # wrong rather than merely untidy -- while cosine stays silent, because the widths
    # agree and that is the only thing it checks.
    assert cosine(first.vectors[summary], second.vectors[summary]) < 0.99
    assert len(first.vectors[summary]) == len(second.vectors[summary])

    # The other direction. A cache that misses on everything would pass all of the
    # above, and would also be no cache at all.
    large.embedded.clear()
    third = build_index(entries(), embedder=large, vector_cache=cache)
    assert large.embedded == [], "the same embedder missed its own cache entry"
    assert list(third.vectors[summary]) == list(first.vectors[summary])
    assert len(cache) == 2

    # `dimensions` is in the key too, and it has to be: `text-embedding-3-large` at two
    # widths is one model name over two incompatible vector spaces.
    narrow = Counting(dimensions=32, salt="stands-in-for-3-large")
    assert narrow.model == large.model
    build_index(entries(), embedder=narrow, vector_cache=cache)
    assert narrow.embedded == [summary]
    assert len(cache) == 3

    # A cache with no embedder cannot form a key at all, so it is refused rather than
    # read under a guessed identity.
    with pytest.raises(ValueError):
        build_index(entries(), vector_cache=cache)


@pytest.mark.parametrize("adapter", ADAPTERS)
def test_the_adapter_reports_the_model_the_provider_actually_used(adapter: str) -> None:
    """The house rule, in the one place it applies to a third party: **the record must
    describe what happened, not what was requested.**

    A provider may serve an alias, a dated snapshot, or a silently upgraded version of the
    name it was asked for. `model` is a comparability knob, so a run that records the
    *requested* name and compares against another that got a different snapshot is v1's
    reasoning-effort incident again: two ladders differing only in a live config field that
    was recorded nowhere, and effort moved the baseline arm **+2.5pp against a 2.3pp
    detection threshold**.

    Assert `adapter.model` reflects what the response reported, and that a mismatch between
    requested and served is **not** silently normalised to the requested string. For the
    deterministic adapter, `model` must be a stable identifier that changes when its
    algorithm changes — a fake whose identity never moves makes every cached vector from
    every past version look current.
    """
    from embedders import NARROW_DIMENSIONS, make_embedder

    embedder = make_embedder(adapter, dimensions=NARROW_DIMENSIONS)

    if adapter == "deterministic":
        from governed_bi.model import DeterministicEmbedder

        # There is no model argument to hand it, so there is nothing for it to echo:
        # the identity is derived from the algorithm rather than requested.
        with pytest.raises(TypeError):
            DeterministicEmbedder(model="text-embedding-3-large")  # type: ignore[call-arg]

        assert embedder.model.startswith("deterministic:hashed-bow-sha256:")

        # Stable across objects, and independent of width -- width is already its own
        # component of every cache key, so folding it in here would double-count it.
        assert embedder.model == DeterministicEmbedder(dimensions=NARROW_DIMENSIONS).model
        assert embedder.model == DeterministicEmbedder(dimensions=NARROW_DIMENSIONS * 4).model

        # ...and it MOVES when the algorithm's behaviour moves.
        assert (
            embedder.model
            != DeterministicEmbedder(dimensions=NARROW_DIMENSIONS, salt="v2").model
        )

        # Pinned, and this is the assertion that makes the sentence above enforceable
        # rather than aspirational: the identity is a digest of the adapter's own output
        # on a fixed probe, so editing the tokeniser, the bucket function, the sign bit
        # or the normalisation turns this line red. A hand-maintained version string is
        # the thing that gets forgotten, and then every cached vector from every past
        # version looks current.
        assert embedder.model == "deterministic:hashed-bow-sha256:daef773fc3d2"
        return

    from openai import OpenAI

    # The requested name is available immediately; the reported one is not. That gap is
    # the observable difference between an adapter that reads the response and one that
    # echoes the request, and it is the only difference visible at all while the
    # provider happens to serve the name it was asked for.
    assert embedder.requested_model == "text-embedding-3-large"
    assert embedder.served_model is None

    observed = OpenAI().embeddings.create(
        model="text-embedding-3-large",
        input=["a customers table"],
        dimensions=NARROW_DIMENSIONS,
    )

    # Independently observed, from a response this adapter never saw.
    assert embedder.model == f"openai:{observed.model}"
    assert embedder.served_model == observed.model
    assert embedder.served_model is not None


def test_the_embedding_knobs_reach_knobs_resolved() -> None:
    """`embedding_model` and `embedding_dimensions` are declared knobs with
    `Role.comparability` (`register/knobs.py:208-212`), and today nothing supplies either,
    because no embedder exists.

    Assert that using an embedder puts both into the resolved knob set, so the serve config
    hash moves when the embedder changes. Without this, two runs differing only in embedder
    compare as one experiment — which is precisely what the knob was declared to prevent,
    and the declaration alone has never stopped anything in this repository.
    """
    from governed_bi.model import DeterministicEmbedder, embedding_knobs
    from governed_bi.register.knobs import (
        comparability_keys,
        config_hash_keys,
        knob_names,
    )

    embedder = DeterministicEmbedder(dimensions=64)
    knobs = embedding_knobs(embedder)

    assert set(knobs) == {"embedding_model", "embedding_dimensions"}
    assert knobs["embedding_model"] == embedder.model
    assert knobs["embedding_dimensions"] == 64

    # Declared, and declared as `comparability` -- so they are IN the config hash rather
    # than recorded beside it. A threshold outside the comparability hash is v1's
    # `serve_config_hash` defect, and a knob name no register backs is the same hole.
    assert set(knobs) <= knob_names()
    assert set(knobs) <= comparability_keys()
    assert set(knobs) <= config_hash_keys()

    base = {"route_top_n": 3, "candidate_depth": 50}
    resolved = {**base, **knobs}
    assert resolved["embedding_model"] == embedder.model
    assert resolved["embedding_dimensions"] == 64

    # Two runs differing ONLY in embedder no longer resolve to the same knob set --
    # neither in the model nor in the width, and the width is the one `cosine` cannot
    # catch when the two models were asked for the same one.
    other_model = {
        **base,
        **embedding_knobs(DeterministicEmbedder(dimensions=64, salt="other")),
    }
    other_width = {**base, **embedding_knobs(DeterministicEmbedder(dimensions=128))}
    assert resolved != other_model
    assert resolved != other_width

    # ...and identical configuration still resolves identically, or the two lines above
    # would also pass for a resolver that simply never repeats itself.
    assert resolved == {**base, **embedding_knobs(DeterministicEmbedder(dimensions=64))}


# ── the deterministic adapter is an adapter, not a fake ───────────────────────


def test_the_deterministic_adapter_is_stable_across_processes() -> None:
    """`ports.py:108` — it *"is what makes ADR 0005's implementation steps 6–9 model-free,
    and it is a third adapter, not a courtesy fake."*

    So it must be **deterministic across processes**, not merely within one: a fake seeded
    from `hash()` is stable inside a run and different in the next, which makes every
    cross-run comparison in a model-free step meaningless while every single-run test
    passes. Python salts `hash()` for `str` per process by default.

    Assert the same text yields the same vector in a **subprocess** with a different
    `PYTHONHASHSEED`, and that two different texts do not collide.
    """
    import json
    import os
    import subprocess
    import sys
    import textwrap

    from governed_bi.model import DeterministicEmbedder

    texts = ["customers registered in 2019", "brewing capacity per site"]
    local = DeterministicEmbedder(dimensions=64)
    expected = [list(v) for v in local.embed(texts)]

    program = textwrap.dedent(
        """
        import json
        from governed_bi.model import DeterministicEmbedder

        texts = ["customers registered in 2019", "brewing capacity per site"]
        embedder = DeterministicEmbedder(dimensions=64)
        print(json.dumps({
            "model": embedder.model,
            "vectors": [list(v) for v in embedder.embed(texts)],
            "builtin_hash": hash(texts[0]),
        }))
        """
    )

    root = Path(__file__).resolve().parent.parent.parent
    runs = []
    for seed in ("0", "12345"):
        completed = subprocess.run(
            [sys.executable, "-c", program],
            env={**os.environ, "PYTHONHASHSEED": seed},
            cwd=str(root),
            capture_output=True,
            text=True,
            check=True,
        )
        runs.append(json.loads(completed.stdout))

    # The control, and it is what stops this body from being a tautology: the two
    # subprocesses really did get different string-hash salts. Without this line, a
    # subprocess mechanism that silently failed to vary the seed would make the
    # agreement below say nothing at all -- which is exactly the state a hash()-seeded
    # fake would be in.
    assert runs[0]["builtin_hash"] != runs[1]["builtin_hash"], (
        "PYTHONHASHSEED did not change the interpreter's string hashing, so this "
        "test cannot distinguish a digest-seeded adapter from a hash()-seeded one"
    )

    for run in runs:
        assert run["vectors"] == expected
        assert run["model"] == local.model

    # Two different texts do not collide.
    assert expected[0] != expected[1]


def test_the_semantic_channel_scores_a_facet_that_declares_it() -> None:
    """The end-to-end reason this parcel exists, and it is **not** schema routing.

    `register/facets.py:116` gives `Stage.facet_example` only `Channel.semantic`. With no
    embedder in the repository, that facet has never been able to retrieve anything at all —
    few-shots are structurally unreachable, which is the same class of defect as v1's
    `NegativeExampleAsset` and as the five wiring hooks in ADR 0005 §2.8.2.

    Assert that with an embedder configured, a few-shot whose text matches the question is
    retrieved, and that its channel state is `ran` rather than `not_configured`.

    **Do not write this expecting a routing improvement.** `register/citations.py:80`
    records the measurement, on this exact model: schema shortlist recall BM25
    0.736@1 / 0.844@3 versus embedding 0.694@1 / 0.852@3, at 57 schemas over all 1351
    questions — BM25 **wins** at @1, and the reason is on record too, that BIRD's
    obfuscation is *translation*, so physical names carry real semantics in the wrong
    language, which is exact for BM25 and weak for cross-lingual embedding. This adapter
    buys a facet that could not run, and fusion (0.871@3); it does not buy routing lift, and
    a test asserting otherwise would fail for a true reason.
    """
    from governed_bi.model import DeterministicEmbedder
    from governed_bi.register.assets import AssetType
    from governed_bi.register.facets import (
        FACET_CHANNELS,
        FACET_TARGETS,
        Channel,
        ChannelState,
        expected_channel_state,
    )
    from governed_bi.register.stages import Stage
    from governed_bi.retrieve.index import IndexEntry, build_index
    from governed_bi.retrieve.semantic import semantic_search

    # The declaration this body is about. One channel, and it is the semantic one, so a
    # few-shot has to be *findable* by cosine rather than merely scored by it once
    # something else has found it.
    assert FACET_CHANNELS[Stage.facet_example] == frozenset({Channel.semantic})
    assert Channel.lexical not in FACET_CHANNELS[Stage.facet_example]
    assert expected_channel_state(Stage.facet_example, Channel.semantic) is ChannelState.ran
    assert FACET_TARGETS[Stage.facet_example] == frozenset({AssetType.few_shot})

    question = "how many customers registered in 2019"

    # Deliberately NOT the question verbatim. An identical summary would let a plain dict
    # lookup pass this body, and what the channel has to do is rank by overlap.
    wanted = IndexEntry(
        id="fs_customers_2019",
        summary="count of customers who registered during 2019",
        asset_type=AssetType.few_shot,
        schema_tag="sales",
    )
    distractor = IndexEntry(
        id="fs_capacity",
        summary="average brewing capacity across factory sites",
        asset_type=AssetType.few_shot,
        schema_tag="sales",
    )
    table = IndexEntry(
        id="sales.kunden",
        summary="kunden (customer records)",
        asset_type=AssetType.table,
        schema_tag="sales",
    )

    embedder = DeterministicEmbedder(dimensions=256)
    index = build_index([wanted, distractor, table], embedder=embedder, vector_cache={})
    query_vector = embedder.embed([question])[0]

    few_shots = {wanted.id, distractor.id}
    hits, state = semantic_search(index, query_vector, candidates=few_shots)

    assert state is ChannelState.ran
    assert [asset_id for asset_id, _ in hits] == [wanted.id, distractor.id]
    assert 0.0 < hits[0][1] < 1.0, (
        "the top score is 0 or an exact match: either the channel found nothing, or the "
        "fixture is matching verbatim and would pass without an embedder at all"
    )
    assert hits[0][1] > hits[1][1]

    # Without an embedder the same call reports `not_configured` -- which is the state
    # this facet has been in for the whole life of the repository, and what made the
    # few-shot structurally unreachable rather than merely unlucky. A channel that
    # reported `ran` here would make "found nothing" and "never wired up" one
    # observation, which is the shape half this repo's retired numbers have.
    bare = build_index([wanted, distractor, table])
    bare_hits, bare_state = semantic_search(bare, query_vector, candidates=few_shots)
    assert bare_state is ChannelState.not_configured
    assert bare_hits == []
