"""Parcel I's acceptance criterion: the `Embedder` port's adapters.

**Written 2026-08-03, before the adapters exist.** `ports.py:96` already names the three
this file governs — `model/openai_embedder.py`, `model/bedrock_embedder.py`,
`model/deterministic_embedder.py` — and states that the deterministic one *"is a third
adapter, not a courtesy fake"*, because it is what makes ADR 0005's implementation steps
6–9 model-free.

**Do not edit this file to make it pass.** If a test looks wrong, stop and say so.

Every specification below is parametrised over **every** adapter, deliberately. One adapter
is a hypothetical seam; the port earns its existence only if two independent
implementations satisfy one contract, and v1's fake discarded the arguments it was handed,
so a contract only the real adapter met would have caught nothing.

The through-line is narrower than usual and it is worth stating, because the port's own
docstring gives the reason it exists: **the model identity and the width are part of the
interface, not metadata beside it.** v1's vector cache omitted both, and `cosine` returned
`0.0` on a width mismatch rather than raising, so a cross-model cache hit degraded routing
to "nothing scores" with no error anywhere. `retrieve/semantic.py:18` now raises on a width
mismatch — which closes the case the widths *differ* and leaves open the one they agree,
which is the case this contract is mostly about.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from contracts import needs  # noqa: E402

#: A specification with no body. Per test, never module-level — see
#: ``tests/serve/test_turn_contract.py`` for the incident that established that.
UNWRITTEN = pytest.mark.xfail(strict=True, reason="contract specified, body not yet written")

pytestmark = [needs("I")]

#: Every adapter, by import path. The OpenAI one must **skip loudly** without a key, naming
#: the environment variable and never printing its value; a silent skip is a green suite
#: that tested one adapter and reported two.
ADAPTERS = ("deterministic", "openai")


# ── the interface, on every adapter ───────────────────────────────────────────


@UNWRITTEN
@pytest.mark.parametrize("adapter", ADAPTERS)
def test_embed_returns_one_vector_per_input_in_input_order(adapter: str) -> None:
    """`ports.py:113` — *"A shorter or reordered result is a bug in the adapter, never
    something the caller reconciles."*

    `retrieve/index.py:131` zips the returned vectors against the texts it asked for with
    `strict=True`, so a **short** result raises. A **reordered** one does not: every asset
    silently gets another asset's vector, every score is wrong, and nothing anywhere
    disagrees. That is the failure this test exists for, and it is invisible to any
    single-input test.

    **Fixture shape.** Embed a list long enough to **cross the adapter's batch boundary** —
    batching is the only place order breaks, so a batch-sized input is the whole point.
    Make each text distinguishable, embed them a second time individually, and assert the
    batched vector for text *i* equals the individual vector for text *i*.

    Equality on floats: OpenAI is not bit-identical across calls, so compare with a
    tolerance, and assert the **nearest neighbour of each individual vector is its own
    batched vector** rather than an exact match. A tolerance loose enough to pass a
    reordering is worse than no test.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
@pytest.mark.parametrize("adapter", ADAPTERS)
def test_every_vector_has_exactly_the_declared_width(adapter: str) -> None:
    """`dimensions` is a property of the port, and `text-embedding-3-large` can be asked
    for a **shortened** width — so "the width the API returned" and "the width the adapter
    declares" are two facts, and only one of them is in the interface.

    Assert they agree: `len(v) == adapter.dimensions` for every returned vector. If the
    adapter accepts a `dimensions` argument, assert it for a shortened width too, because a
    request the API ignored would otherwise pass unnoticed.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
@pytest.mark.parametrize("adapter", ADAPTERS)
def test_an_empty_or_whitespace_input_refuses(adapter: str) -> None:
    """`ports.py:118` states the hazard and the reason it cannot be papered over: *OpenAI
    accepts it and returns a vector that can score above zero and pollute a ranking*, while
    Bedrock rejects it. So the adapters would disagree, and the disagreement would surface
    as a ranking that is subtly wrong on one provider only.

    The port says callers must not pass one. **The adapter must refuse anyway** — a rule
    only the caller enforces is a rule that holds until a new caller exists. Assert both
    `""` and `"   "` raise, on every adapter, and assert **nothing is returned** rather than
    a zero vector: a zero vector is "not measured" rendered as "scores nothing", and
    `cosine` cannot distinguish it from a real vector that happens to be orthogonal.
    """
    pytest.fail("not implemented: see docstring")


# ── the cache key, which is where v1 actually died ────────────────────────────


@UNWRITTEN
def test_two_models_of_the_same_width_do_not_share_a_cache_entry() -> None:
    """**The most important test in this file, and the one the existing fix does not
    cover.**

    `retrieve/index.py:103` takes `vector_cache: Mapping[str, Vector]` keyed on the
    **summary text alone**. `register/knobs.py:208` says `embedding_model` is *"part of
    every vector cache key"*. Those two statements contradict each other, and `cosine`
    raising on a width mismatch (`semantic.py:18`) closes only the case where the widths
    **differ**.

    `text-embedding-3-large` accepts a `dimensions` argument. So a 1536-wide
    `text-embedding-3-large` and a 1536-wide `text-embedding-3-small` are **width-identical
    and semantically unrelated**, and the one backstop in the system cannot tell them apart.
    That is v1's defect surviving in the exact shape the fix does not reach.

    Assert that a cache populated by one model is not reused by another of the same width.
    Wherever the key is formed, `(model, dimensions, text)` must be in it — not text alone.

    **This is a specification about a signature, not only a behaviour.** If satisfying it
    means changing `build_index`'s `vector_cache` parameter, change it; a cache that is
    correct only when the caller remembers to keep one dict per model is the convention this
    port exists to replace.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
@pytest.mark.parametrize("adapter", ADAPTERS)
def test_the_adapter_reports_the_model_the_provider_actually_used(adapter: str) -> None:
    """The house rule, in the one place it applies to a third party: **the record must
    describe what happened, not what was requested.**

    A provider may serve an alias, a dated snapshot, or a silently upgraded version of the
    name it was asked for. `model` is a comparability knob, so a run that records the
    *requested* name and compares against another that got a different snapshot is v1's
    reasoning-effort incident again: two ladders differing only in a live config field that
    was recorded nowhere, and effort moved the baseline arm **+2.5pp against a 2.3pp
    detection threshold**.

    Assert `adapter.model` reflects what the response reported, and that a mismatch between
    requested and served is **not** silently normalised to the requested string. For the
    deterministic adapter, `model` must be a stable identifier that changes when its
    algorithm changes — a fake whose identity never moves makes every cached vector from
    every past version look current.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_the_embedding_knobs_reach_knobs_resolved() -> None:
    """`embedding_model` and `embedding_dimensions` are declared knobs with
    `Role.comparability` (`register/knobs.py:208-212`), and today nothing supplies either,
    because no embedder exists.

    Assert that using an embedder puts both into the resolved knob set, so the serve config
    hash moves when the embedder changes. Without this, two runs differing only in embedder
    compare as one experiment — which is precisely what the knob was declared to prevent,
    and the declaration alone has never stopped anything in this repository.
    """
    pytest.fail("not implemented: see docstring")


# ── the deterministic adapter is an adapter, not a fake ───────────────────────


@UNWRITTEN
def test_the_deterministic_adapter_is_stable_across_processes() -> None:
    """`ports.py:108` — it *"is what makes ADR 0005's implementation steps 6–9 model-free,
    and it is a third adapter, not a courtesy fake."*

    So it must be **deterministic across processes**, not merely within one: a fake seeded
    from `hash()` is stable inside a run and different in the next, which makes every
    cross-run comparison in a model-free step meaningless while every single-run test
    passes. Python salts `hash()` for `str` per process by default.

    Assert the same text yields the same vector in a **subprocess** with a different
    `PYTHONHASHSEED`, and that two different texts do not collide.
    """
    pytest.fail("not implemented: see docstring")


@UNWRITTEN
def test_the_semantic_channel_scores_a_facet_that_declares_it() -> None:
    """The end-to-end reason this parcel exists, and it is **not** schema routing.

    `register/facets.py:116` gives `Stage.facet_example` only `Channel.semantic`. With no
    embedder in the repository, that facet has never been able to retrieve anything at all —
    few-shots are structurally unreachable, which is the same class of defect as v1's
    `NegativeExampleAsset` and as the five wiring hooks in ADR 0005 §2.8.2.

    Assert that with an embedder configured, a few-shot whose text matches the question is
    retrieved, and that its channel state is `ran` rather than `not_configured`.

    **Do not write this expecting a routing improvement.** `register/citations.py:80`
    records the measurement, on this exact model: schema shortlist recall BM25
    0.736@1 / 0.844@3 versus embedding 0.694@1 / 0.852@3, at 57 schemas over all 1351
    questions — BM25 **wins** at @1, and the reason is on record too, that BIRD's
    obfuscation is *translation*, so physical names carry real semantics in the wrong
    language, which is exact for BM25 and weak for cross-lingual embedding. This adapter
    buys a facet that could not run, and fusion (0.871@3); it does not buy routing lift, and
    a test asserting otherwise would fail for a true reason.
    """
    pytest.fail("not implemented: see docstring")
