"""Parcel D's acceptance criterion: the asset types, their validation, and the store.

**Do not edit this file to make it pass.** It is the contract, authored by the design
holder before implementation, because an agent writes tests that pass against the code
it just wrote. If a test looks wrong, say so and stop.

Specification: ADR 0005 §1. The two invariants everything here turns on:

* **I1 — ``summary`` is the only indexed field.** Bounded at 250 characters. A
  validator that lets a 4,000-character summary through has broken the index, not
  bent a style rule: the index is a shared scoring space, and one enormous entry
  changes what every other entry's score means.
* **I2 — ``body`` is what the system uses on hit.** Unbounded, and **optional**. The
  seed produces assets with no body at all; a validator that requires one makes
  ADR 0005's "steps 6-9 are measurable with no model" false.

Hence ``(assets, problems)``, with both halves load-bearing: a raise on the first
bad file loses the rest of the build; a silent skip hides how much was lost.

**Three tests were removed from this file on 2026-08-03, deliberately.** They asserted
default-deny sanitization of corpus prose — a control that was specified, built, and
then deleted, because the corpus is trusted and the incoming question is not: injection
is checked once at the analyst's input by ``govern.guard``. Sanitizing on ``load`` also
changed what reached the model while ``corpus_content_hash``, taken over the files on
disk, did not move. See **ADR 0005 §1.6**. Recorded here because an acceptance file
that quietly loses three tests cannot be told from one that was weakened to pass.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from contracts import needs  # noqa: E402

pytestmark = needs("D")


@pytest.fixture
def store():
    from governed_bi.corpus import store  # type: ignore[import-not-found]

    return store


@pytest.fixture
def valid_asset_yaml() -> str:
    """One minimal table asset that must load. Kept in one place so the negative tests
    below differ from it in exactly one way."""
    return (
        "asset_type: table\n"
        "id: beer_factory.customers\n"
        "schema: beer_factory\n"
        "physical_name: customers\n"
        "summary: customers - one row per registered buyer\n"
    )


# ── per-item error isolation, in both directions ─────────────────────────────


def test_one_unparseable_file_does_not_discard_the_others(store, tmp_path, valid_asset_yaml) -> None:
    """The 69-schema incident. A truncated YAML must cost one asset, not the build."""
    (tmp_path / "good.yaml").write_text(valid_asset_yaml, encoding="utf-8")
    (tmp_path / "truncated.yaml").write_text("asset_type: table\nid: beer_factory.orders\nsum", encoding="utf-8")

    assets, problems = store.load(tmp_path)
    assert len(assets) == 1, "the parseable asset must survive its neighbour"
    assert len(problems) == 1


def test_load_never_raises_for_a_bad_item(store, tmp_path) -> None:
    """Not merely "isolates errors" — must not raise at all. v1's call site was a
    ``try/finally`` with no ``except``, so a raise here was unrecoverable one frame up."""
    (tmp_path / "a.yaml").write_text("{{{ not yaml", encoding="utf-8")
    (tmp_path / "b.yaml").write_text("asset_type: nonesuch\nid: x\n", encoding="utf-8")
    assets, problems = store.load(tmp_path)
    assert assets == [] or len(assets) == 0
    assert len(problems) == 2


def test_a_problem_names_the_file_and_the_reason(store, tmp_path) -> None:
    """A silent skip is the other half of the defect. A problem a reader cannot act on
    is a silent skip with extra steps."""
    (tmp_path / "truncated.yaml").write_text("asset_type: table\nid: x\nsum", encoding="utf-8")
    _, problems = store.load(tmp_path)
    rendered = " ".join(str(p) for p in problems)
    assert "truncated.yaml" in rendered


def test_an_empty_directory_is_not_an_error_but_is_reported(store, tmp_path) -> None:
    """Zero assets from an empty tree is correct. Zero assets **silently** is how "the
    corpus lost half its assets" reads as "the corpus is small"."""
    assets, problems = store.load(tmp_path)
    assert assets == [] or len(assets) == 0
    assert not problems, "an empty directory is not a per-item problem"


# ── I1 and I2 ────────────────────────────────────────────────────────────────


def test_a_summary_over_250_chars_is_rejected(store, tmp_path) -> None:
    """I1. The index is a shared scoring space; one huge entry changes every other
    entry's score."""
    yaml = (
        "asset_type: table\nid: beer_factory.customers\nschema: beer_factory\n"
        f"physical_name: customers\nsummary: {'x' * 251}\n"
    )
    (tmp_path / "wide.yaml").write_text(yaml, encoding="utf-8")
    assets, problems = store.load(tmp_path)
    assert len(problems) == 1 and not assets


def test_an_asset_with_no_body_is_valid(store, tmp_path, valid_asset_yaml) -> None:
    """I2. The seed produces exactly this. Requiring a body makes ADR 0005's
    "measurable with no model at all" false, and that claim is the reason the seed
    exists."""
    (tmp_path / "seeded.yaml").write_text(valid_asset_yaml, encoding="utf-8")
    assets, problems = store.load(tmp_path)
    assert len(assets) == 1 and not problems


def test_an_unbounded_body_is_valid(store, tmp_path, valid_asset_yaml) -> None:
    """I2 again, from the other side: long knowledge has an unbounded home that costs
    prompt tokens rather than recall. Only ``summary`` is bounded."""
    yaml = valid_asset_yaml + "body: |\n" + "".join(f"  line {i}\n" for i in range(500))
    (tmp_path / "rich.yaml").write_text(yaml, encoding="utf-8")
    assets, problems = store.load(tmp_path)
    assert len(assets) == 1, problems


def test_a_column_summary_may_drop_the_table_qualifier(store, tmp_path) -> None:
    """Decision #6. The seed writes ``table.column (text)`` because at seed time there
    is nothing better, and a curator rewriting it shorter **must not fail validation**
    for dropping the qualifier — the table association comes from the tag rule, not
    from prose."""
    yaml = (
        "asset_type: column\nid: beer_factory.customers.email\nschema: beer_factory\n"
        "physical_name: email\nparent_table: customers\n"
        "summary: email - contact address, unique per customer\n"
    )
    (tmp_path / "col.yaml").write_text(yaml, encoding="utf-8")
    assets, problems = store.load(tmp_path)
    assert len(assets) == 1, problems


# ── the content hash ─────────────────────────────────────────────────────────


def test_the_content_hash_has_no_unknown_sentinel(tmp_path, valid_asset_yaml) -> None:
    """v1's ``corpus_content_hash == "unknown"`` compared equal to itself, so two runs
    with **no recorded treatment** passed the comparability gate. There must be no
    in-band value meaning "I do not know"."""
    from governed_bi.corpus.hash import corpus_content_hash  # type: ignore[import-not-found]

    (tmp_path / "a.yaml").write_text(valid_asset_yaml, encoding="utf-8")
    digest = corpus_content_hash(tmp_path)
    assert "unknown" not in str(digest).lower()


def test_the_content_hash_changes_when_content_changes(tmp_path, valid_asset_yaml) -> None:
    """The hash IS the treatment identity: ADR 0005's delivery gate reads it to prove
    two arms received different corpora. A hash insensitive to content would let the
    v1 ladder that compared two byte-identical arms pass again."""
    from governed_bi.corpus.hash import corpus_content_hash  # type: ignore[import-not-found]

    path = tmp_path / "a.yaml"
    path.write_text(valid_asset_yaml, encoding="utf-8")
    before = corpus_content_hash(tmp_path)
    path.write_text(valid_asset_yaml.replace("registered buyer", "registered purchaser"), encoding="utf-8")
    assert corpus_content_hash(tmp_path) != before


def test_the_content_hash_is_stable_across_calls(tmp_path, valid_asset_yaml) -> None:
    """The complement. A hash that changes every call also satisfies the test above and
    would make every comparison incomparable — which reads as "the treatment differed"
    and passes the delivery gate for the wrong reason."""
    from governed_bi.corpus.hash import corpus_content_hash  # type: ignore[import-not-found]

    (tmp_path / "a.yaml").write_text(valid_asset_yaml, encoding="utf-8")
    assert corpus_content_hash(tmp_path) == corpus_content_hash(tmp_path)
