"""Parcel B's acceptance criterion: one test per bypass in ADR 0006's B1-B10.

**Read this before implementing ``govern/``.** These are not examples. ADR 0006 exists
because an audit of the v1 design found ten distinct ways to reach the database with
SQL that had cleared no layer, and a governance layer that closes nine of them is not
90% of a governance layer. Each test below names its bypass; the ADR's §-numbered
entry for that bypass is the specification.

**Do not edit this file to make it pass.** If a test looks wrong, say so and stop — a
disagreement here is a disagreement about the spec, and the spec is the thing being
implemented. Adjusting the criterion to fit the code is how v1's gold gate ended up
passing with the comparison reversed.

Two of these are worth flagging because they are *not* v1 incidents and will look
paranoid:

* **B2** was found reviewing ADR 0006's own first draft, whose allowlist admitted it.
  ``json_agg(t)`` emits every column of a row while producing **zero ``Column`` nodes**,
  so an AST walk looking for ``Column`` sees nothing to reject and passes it.
* **B8**'s regex clause. Python's ``$`` also matches before a trailing newline, so
  ``"beer_factory\\n"`` clears a ``^...$`` validator and then names a directory.
  ``\\A...\\Z`` is required.

The interface under test is ADR 0006 §3:

.. code-block:: python

    def check(sql, *, corpus, licensed, default_schema, dialect, policy) -> Verdict
    def guard(question, knobs) -> GuardVerdict

A verdict carries **the layer that refused and the rule id**, never a bare bool:
``register/stages.py`` maps ``refused_by`` to a stage and an outcome, and a bool cannot
feed it. B3 is the incident — a ledger entry written before ``check()`` ran carried no
layer, graded delivery read ``failed_layer=None``, treated it as non-hard, and
re-executed SQL that had cleared nothing.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from contracts import needs  # noqa: E402

pytestmark = needs("B")

BLOCKED = "must be blocked, and by a named layer"


@pytest.fixture
def check():
    from governed_bi.govern.check import check  # type: ignore[import-not-found]

    return check


@pytest.fixture
def layer():
    from governed_bi.govern.layers import Layer  # type: ignore[import-not-found]

    return Layer


# ── the enum's shape is load-bearing ─────────────────────────────────────────


def test_layers_are_ordered_and_have_no_fractional_members(layer) -> None:
    """``check()`` returns on first failure, so reaching layer N proves 1..N-1 passed.

    The first draft bolted the function allowlist on as "L1.5", which cannot be
    represented in an ordered verdict — a block by it would have had to report
    ``None``, which is B3 through the front door.
    """
    assert [m.value for m in layer] == [1, 2, 3, 4, 5, 6, 7]
    assert layer.FUNCTIONS < layer.BINDING < layer.COLUMNS < layer.TABLES


def test_a_verdict_never_reports_none_for_a_block(check, layer) -> None:
    """B3. ``failed_layer=None`` must mean **passed**, with no third state.

    v1's cap path produced a verdict with no layer, graded delivery read it as
    non-hard, and card-number SQL would have reached the gateway.
    """
    verdict = check("DROP TABLE customers", licensed=frozenset({"customers"}))
    assert verdict["passed"] is False
    assert verdict["failed_layer"] is not None, BLOCKED


def test_layers_evaluated_distinguishes_did_not_run_from_passed(check) -> None:
    """A layer with no entry **did not run**. Absence is not agreement -- L-R1."""
    verdict = check("DROP TABLE customers", licensed=frozenset({"customers"}))
    assert len(verdict["layers_evaluated"]) < 7


# ── B1-B10 ───────────────────────────────────────────────────────────────────


@pytest.mark.parametrize(
    "sql",
    [
        "SELECT pg_read_file('/etc/passwd')",
        "SELECT query_to_xml('SELECT * FROM customers', true, false, '')",
        "SELECT table_to_xml('customers', true, false, '')",
        "SELECT database_to_xml(true, false, '')",
        "SELECT setval('customers_id_seq', 1)",
        "SELECT nextval('customers_id_seq')",
    ],
)
def test_b1_column_less_calls_are_blocked(check, sql) -> None:
    """B1. No table and no column referenced, so the column and table layers are
    structurally blind. A read-only connection does not help: these are reads. The
    XML-export family takes its target as a **string literal**, which sqlglot parses as
    ``exp.Anonymous``, and one call dumps a whole table."""
    assert check(sql, licensed=frozenset({"customers"}))["passed"] is False, BLOCKED


@pytest.mark.parametrize(
    "sql",
    [
        "SELECT json_agg(t) FROM customers t",
        "SELECT row_to_json(t) FROM customers t",
        "SELECT array_agg(t) FROM customers t",
        "SELECT to_jsonb(t) FROM customers t",
        "SELECT count(t.*) FROM customers t",
    ],
)
def test_b2_whole_row_aggregates_are_blocked(check, sql) -> None:
    """B2. Every one of these emits every column of the row — **including excluded and
    suspect ones** — while producing zero ``Column`` nodes for them. An allowlist that
    walks the AST for ``Column`` finds nothing to object to.

    Not a v1 incident: found reviewing ADR 0006's own first draft, which permitted it.
    """
    assert check(sql, licensed=frozenset({"customers"}))["passed"] is False, BLOCKED


def test_b4_a_missing_allowlist_refuses_rather_than_falling_through(check) -> None:
    """B4. v1 wrapped the pre-execute recheck in ``if allowlist is not None``, so a
    missing argument fell through to ``gateway.execute`` — the guard added to make the
    path defence-in-depth had removed the only authorization on it.

    Absent must mean refuse, never permit. Whether that is an exception or a failed
    verdict is the implementer's call; silently passing is not.
    """
    with pytest.raises(Exception):
        result = check("SELECT id FROM customers", licensed=None)
        assert result["passed"] is False, BLOCKED


def test_b4_sibling_an_empty_licensed_set_is_not_a_wildcard(check) -> None:
    """The `if not allowlist` reading of the same defect. An empty set licenses
    nothing; it is not "no restriction"."""
    assert check("SELECT id FROM customers", licensed=frozenset())["passed"] is False, BLOCKED


@pytest.mark.parametrize("spelling", ["customerid", "CUSTOMERID", "CustomerId"])
def test_b5_case_folding_does_not_clear_an_allowlist(check, spelling) -> None:
    """B5. Postgres folds unquoted identifiers, so ``customerid`` clears a
    ``CustomerID`` allowlist — and quoting the model's spelling then sends the engine a
    column that does not exist. Fold **both** sides consistently; do not quote to
    compensate."""
    verdict = check(
        f"SELECT {spelling} FROM customers",
        licensed=frozenset({"customers"}),
        allowed_columns=frozenset({"customers.CustomerID"}),
    )
    assert verdict["passed"] is True, "a fold-equal column must be permitted, not quoted around"


def test_b6_three_part_references_are_bound_not_just_matched(check) -> None:
    """B6. ``schema.table.column`` slipped past the column layer — the key *is* in the
    lake-wide allowlist — and past the table layer, which inspects only FROM sources.

    The fix is that every reference must **bind to exactly one in-scope source**
    (layer BINDING) before the column layer is consulted. Matching a string against an
    allowlist is not binding.
    """
    verdict = check(
        "SELECT other_schema.secrets.token FROM customers",
        licensed=frozenset({"customers"}),
        allowed_columns=frozenset({"secrets.token", "customers.id"}),
    )
    assert verdict["passed"] is False, BLOCKED


@pytest.mark.parametrize(
    "sql",
    [
        "SELECT * FROM customers",
        "SELECT c.* FROM customers c",
        "SELECT id FROM customers NATURAL JOIN orders",
    ],
)
def test_b6_siblings_star_and_natural_join(check, sql) -> None:
    """A star projection and a ``NATURAL JOIN`` both expand to columns the SQL never
    names, so neither can be column-checked as written."""
    verdict = check(sql, licensed=frozenset({"customers", "orders"}))
    assert verdict["passed"] is False, BLOCKED


@pytest.mark.parametrize(
    "raw",
    ["beer_factory\n", "../etc", "a/b", "..", "", "beer factory", "beer_factory\r\n"],
)
def test_b8_schema_identifiers_are_anchored_with_A_and_Z(raw) -> None:
    """B8. The write directory is derived from ``asset.schema``.

    ``\\A...\\Z``, not ``^...$``: Python's ``$`` also matches before a trailing newline,
    so ``"beer_factory\\n"`` clears a ``^...$`` validator and then names a directory.

    **v2 makes this worse rather than better** — ``SchemaAsset.name`` is a first-class
    field, ``POST /corpus/edit`` is retained, and ADR 0005 §1.5 acknowledges the corpus
    is partly model-authored. So this is reachable from model output.
    """
    from governed_bi.govern.identifiers import is_valid_schema_id  # type: ignore[import-not-found]

    assert is_valid_schema_id(raw) is False, f"{raw!r} must be rejected"


def test_b8_a_legitimate_identifier_still_passes() -> None:
    """The complement. A validator that rejects everything also passes the test above,
    and would be discovered only when the corpus stopped loading."""
    from governed_bi.govern.identifiers import is_valid_schema_id  # type: ignore[import-not-found]

    assert is_valid_schema_id("beer_factory") is True


# ── the allowlist is positive, content-hashed, and version-pinned ────────────


def test_the_function_allowlist_is_positive_not_a_denylist(check) -> None:
    """An invented function name must be refused because it is **not permitted**, not
    because it appears on a list of known-bad names. A denylist cannot enumerate the
    Postgres surface, and B1's XML family is the proof."""
    verdict = check("SELECT pg_sleep_totally_new(1) FROM customers", licensed=frozenset({"customers"}))
    assert verdict["passed"] is False, BLOCKED


def test_a_plain_analytic_query_passes(check) -> None:
    """The control, and it is not optional.

    Every test above is satisfied by ``def check(...): return {"passed": False}``. This
    is the one that makes the others mean something — v1 shipped a refuse-gate nobody
    had measured the false-positive rate of.
    """
    verdict = check(
        "SELECT c.id, count(*) AS n FROM customers c JOIN orders o ON o.cid = c.id "
        "GROUP BY c.id ORDER BY n DESC LIMIT 10",
        licensed=frozenset({"customers", "orders"}),
        allowed_columns=frozenset({"customers.id", "orders.cid"}),
    )
    assert verdict["passed"] is True, verdict
    assert verdict["failed_layer"] is None
